package org.zgif.model.datatype.enumeration;

public enum DepositType {
	NOT_AVAILABLE, CASH_BOND, BONDED_SAVINGS_ACCOUNT_PASS_BOOK, ASSIGNMENT_FOR_SECURITY, GUARANTEE_OF_PAYMENT_OF_A_LOAN, GUARANTEE_PAYMENT_INSURANCE
}
