package org.zgif.model.datatype.enumeration;

public enum OccupancyState {
	RENTED_AND_OCCUPIED_LEASER, RENTED_AND_OCCUPIED_OWNER, RENTED_NOT_OCCUPIED, OUTSTANDING_RENT_WRITTEN_OFF, PREARRANGED, VACANCY
}
