package org.zgif.model.datatype.enumeration;

public enum Sector {
	NOT_AVAILABLE, AUTOMOTIVE, CARRIYING, FINANCIAL, PHARMACEUTICAL, BUILDING, CONSUMER_GOODS, RETAIL, GASTRONOMY, INSURANCE, ENGINEERING_RESOURCES, TECHNOLOGY, UTILITIES, CONSULTING, AUTHORITIES, MEDIA, MEDICAL, OTHERS
}
