package org.zgif.model.datatype.enumeration;

public enum UseType {
	NOT_SPECIFIED, RETAIL, GASTRONOMY, OFFICE, INDUSTRY, PRODUCTION, RESIDENTIAL, WAREHOUSES_HALLS_LOGISTICS, HOTEL, LEISURE, INDOOR_PARKING, OUTDOOR_PARKING, OTHER
}
