//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApartmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ApartmentType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="ROOF_STOREY"/>
 *     &lt;enumeration value="LOFT"/>
 *     &lt;enumeration value="MAISONETTE"/>
 *     &lt;enumeration value="PENTHOUSE"/>
 *     &lt;enumeration value="TERRACED_FLAT"/>
 *     &lt;enumeration value="GROUND_FLAT"/>
 *     &lt;enumeration value="APARTMENT"/>
 *     &lt;enumeration value="RAISED_GROUND_FLOOR"/>
 *     &lt;enumeration value="HALF_BASEMENT"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ApartmentType")
@XmlEnum
public enum ApartmentType {

    ROOF_STOREY,
    LOFT,
    MAISONETTE,
    PENTHOUSE,
    TERRACED_FLAT,
    GROUND_FLAT,
    APARTMENT,
    RAISED_GROUND_FLOOR,
    HALF_BASEMENT,
    OTHER;

    public String value() {
        return name();
    }

    public static ApartmentType fromValue(String v) {
        return valueOf(v);
    }

}
