//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssetCategory">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NOT_SPECIFIED"/>
 *     &lt;enumeration value="CAPITAL"/>
 *     &lt;enumeration value="WORKING"/>
 *     &lt;enumeration value="LEASING"/>
 *     &lt;enumeration value="ADMINISTRATION"/>
 *     &lt;enumeration value="GERMAN_CONDOMINIUM_ACT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssetCategory")
@XmlEnum
public enum AssetCategory {

    NOT_SPECIFIED,
    CAPITAL,
    WORKING,
    LEASING,
    ADMINISTRATION,
    GERMAN_CONDOMINIUM_ACT;

    public String value() {
        return name();
    }

    public static AssetCategory fromValue(String v) {
        return valueOf(v);
    }

}
