//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DunningLevel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DunningLevel">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NOT_AVAILABLE"/>
 *     &lt;enumeration value="FIRST_REMINDER"/>
 *     &lt;enumeration value="SECOND_REMINDER"/>
 *     &lt;enumeration value="TERMINATION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DunningLevel")
@XmlEnum
public enum DunningLevel {

    NOT_AVAILABLE,
    FIRST_REMINDER,
    SECOND_REMINDER,
    TERMINATION;

    public String value() {
        return name();
    }

    public static DunningLevel fromValue(String v) {
        return valueOf(v);
    }

}
