//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IssuanceReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IssuanceReason">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NEW_CONSTRUCTION"/>
 *     &lt;enumeration value="MODERNISATION"/>
 *     &lt;enumeration value="RENT_SALE"/>
 *     &lt;enumeration value="NOTICE_PUBLIC_BUILDING"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IssuanceReason")
@XmlEnum
public enum IssuanceReason {

    NEW_CONSTRUCTION,
    MODERNISATION,
    RENT_SALE,
    NOTICE_PUBLIC_BUILDING,
    OTHER;

    public String value() {
        return name();
    }

    public static IssuanceReason fromValue(String v) {
        return valueOf(v);
    }

}
