//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for Land complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Land">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="areaMeasurement" type="{}AreaMeasurement" minOccurs="0"/>
 *         &lt;element name="areaType" type="{}AreaType" minOccurs="0"/>
 *         &lt;element name="assetAccountType" type="{}AssetAccountType" minOccurs="0"/>
 *         &lt;element name="buildingPermission" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="courtage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="demolition" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="fairValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="gfz" type="{}iTYPE_DECIMAL" minOccurs="0"/>
 *         &lt;element name="grz" type="{}iTYPE_DECIMAL" minOccurs="0"/>
 *         &lt;element name="monumentProtectionCategory" type="{}MonumentsType" minOccurs="0"/>
 *         &lt;element name="numberOfParkingSpaces" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="ownerOccupation" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="plotArea" type="{}Area" minOccurs="0"/>
 *         &lt;element name="propertyManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="purchaseDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="purchaseGrossPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseNetPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="riskStyle" type="{}RiskSegment" minOccurs="0"/>
 *         &lt;element name="saleGrossPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="saleNetPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="shortTermConstructible" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="siteConstructibleType" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="siteDevelopmentType" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="address" type="{}Address" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *         &lt;element name="hashUnits" type="{}HashUnits" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Land", propOrder = {
    "areaMeasurement",
    "areaType",
    "assetAccountType",
    "buildingPermission",
    "courtage",
    "demolition",
    "fairValue",
    "gfz",
    "grz",
    "monumentProtectionCategory",
    "numberOfParkingSpaces",
    "ownerOccupation",
    "plotArea",
    "propertyManager",
    "purchaseDate",
    "purchaseGrossPrice",
    "purchaseNetPrice",
    "riskStyle",
    "saleGrossPrice",
    "saleNetPrice",
    "shortTermConstructible",
    "siteConstructibleType",
    "siteDevelopmentType",
    "address",
    "extensionMap",
    "hashUnits"
})
public class Land
    extends AbstractEntityNode
{

    @XmlSchemaType(name = "string")
    protected AreaMeasurement areaMeasurement;
    @XmlSchemaType(name = "string")
    protected AreaType areaType;
    @XmlSchemaType(name = "string")
    protected AssetAccountType assetAccountType;
    protected Boolean buildingPermission;
    protected Amount courtage;
    protected Boolean demolition;
    protected Amount fairValue;
    protected BigDecimal gfz;
    protected BigDecimal grz;
    @XmlSchemaType(name = "string")
    protected MonumentsType monumentProtectionCategory;
    protected BigInteger numberOfParkingSpaces;
    protected Boolean ownerOccupation;
    protected Area plotArea;
    protected String propertyManager;
    protected String purchaseDate;
    protected Amount purchaseGrossPrice;
    protected Amount purchaseNetPrice;
    @XmlSchemaType(name = "string")
    protected RiskSegment riskStyle;
    protected Amount saleGrossPrice;
    protected Amount saleNetPrice;
    protected Boolean shortTermConstructible;
    protected String siteConstructibleType;
    protected String siteDevelopmentType;
    protected Address address;
    protected ExtensionMap extensionMap;
    protected HashUnits hashUnits;

    /**
     * Gets the value of the areaMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link AreaMeasurement }
     *     
     */
    public AreaMeasurement getAreaMeasurement() {
        return areaMeasurement;
    }

    /**
     * Sets the value of the areaMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaMeasurement }
     *     
     */
    public void setAreaMeasurement(AreaMeasurement value) {
        this.areaMeasurement = value;
    }

    /**
     * Gets the value of the areaType property.
     * 
     * @return
     *     possible object is
     *     {@link AreaType }
     *     
     */
    public AreaType getAreaType() {
        return areaType;
    }

    /**
     * Sets the value of the areaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaType }
     *     
     */
    public void setAreaType(AreaType value) {
        this.areaType = value;
    }

    /**
     * Gets the value of the assetAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link AssetAccountType }
     *     
     */
    public AssetAccountType getAssetAccountType() {
        return assetAccountType;
    }

    /**
     * Sets the value of the assetAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetAccountType }
     *     
     */
    public void setAssetAccountType(AssetAccountType value) {
        this.assetAccountType = value;
    }

    /**
     * Gets the value of the buildingPermission property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBuildingPermission() {
        return buildingPermission;
    }

    /**
     * Sets the value of the buildingPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBuildingPermission(Boolean value) {
        this.buildingPermission = value;
    }

    /**
     * Gets the value of the courtage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getCourtage() {
        return courtage;
    }

    /**
     * Sets the value of the courtage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setCourtage(Amount value) {
        this.courtage = value;
    }

    /**
     * Gets the value of the demolition property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDemolition() {
        return demolition;
    }

    /**
     * Sets the value of the demolition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDemolition(Boolean value) {
        this.demolition = value;
    }

    /**
     * Gets the value of the fairValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getFairValue() {
        return fairValue;
    }

    /**
     * Sets the value of the fairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setFairValue(Amount value) {
        this.fairValue = value;
    }

    /**
     * Gets the value of the gfz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGfz() {
        return gfz;
    }

    /**
     * Sets the value of the gfz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGfz(BigDecimal value) {
        this.gfz = value;
    }

    /**
     * Gets the value of the grz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrz() {
        return grz;
    }

    /**
     * Sets the value of the grz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrz(BigDecimal value) {
        this.grz = value;
    }

    /**
     * Gets the value of the monumentProtectionCategory property.
     * 
     * @return
     *     possible object is
     *     {@link MonumentsType }
     *     
     */
    public MonumentsType getMonumentProtectionCategory() {
        return monumentProtectionCategory;
    }

    /**
     * Sets the value of the monumentProtectionCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonumentsType }
     *     
     */
    public void setMonumentProtectionCategory(MonumentsType value) {
        this.monumentProtectionCategory = value;
    }

    /**
     * Gets the value of the numberOfParkingSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfParkingSpaces() {
        return numberOfParkingSpaces;
    }

    /**
     * Sets the value of the numberOfParkingSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfParkingSpaces(BigInteger value) {
        this.numberOfParkingSpaces = value;
    }

    /**
     * Gets the value of the ownerOccupation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOwnerOccupation() {
        return ownerOccupation;
    }

    /**
     * Sets the value of the ownerOccupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwnerOccupation(Boolean value) {
        this.ownerOccupation = value;
    }

    /**
     * Gets the value of the plotArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getPlotArea() {
        return plotArea;
    }

    /**
     * Sets the value of the plotArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setPlotArea(Area value) {
        this.plotArea = value;
    }

    /**
     * Gets the value of the propertyManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyManager() {
        return propertyManager;
    }

    /**
     * Sets the value of the propertyManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyManager(String value) {
        this.propertyManager = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDate(String value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the purchaseGrossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseGrossPrice() {
        return purchaseGrossPrice;
    }

    /**
     * Sets the value of the purchaseGrossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseGrossPrice(Amount value) {
        this.purchaseGrossPrice = value;
    }

    /**
     * Gets the value of the purchaseNetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseNetPrice() {
        return purchaseNetPrice;
    }

    /**
     * Sets the value of the purchaseNetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseNetPrice(Amount value) {
        this.purchaseNetPrice = value;
    }

    /**
     * Gets the value of the riskStyle property.
     * 
     * @return
     *     possible object is
     *     {@link RiskSegment }
     *     
     */
    public RiskSegment getRiskStyle() {
        return riskStyle;
    }

    /**
     * Sets the value of the riskStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskSegment }
     *     
     */
    public void setRiskStyle(RiskSegment value) {
        this.riskStyle = value;
    }

    /**
     * Gets the value of the saleGrossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleGrossPrice() {
        return saleGrossPrice;
    }

    /**
     * Sets the value of the saleGrossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleGrossPrice(Amount value) {
        this.saleGrossPrice = value;
    }

    /**
     * Gets the value of the saleNetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleNetPrice() {
        return saleNetPrice;
    }

    /**
     * Sets the value of the saleNetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleNetPrice(Amount value) {
        this.saleNetPrice = value;
    }

    /**
     * Gets the value of the shortTermConstructible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShortTermConstructible() {
        return shortTermConstructible;
    }

    /**
     * Sets the value of the shortTermConstructible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShortTermConstructible(Boolean value) {
        this.shortTermConstructible = value;
    }

    /**
     * Gets the value of the siteConstructibleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteConstructibleType() {
        return siteConstructibleType;
    }

    /**
     * Sets the value of the siteConstructibleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteConstructibleType(String value) {
        this.siteConstructibleType = value;
    }

    /**
     * Gets the value of the siteDevelopmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteDevelopmentType() {
        return siteDevelopmentType;
    }

    /**
     * Sets the value of the siteDevelopmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteDevelopmentType(String value) {
        this.siteDevelopmentType = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the extensionMap property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionMap }
     *     
     */
    public ExtensionMap getExtensionMap() {
        return extensionMap;
    }

    /**
     * Sets the value of the extensionMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionMap }
     *     
     */
    public void setExtensionMap(ExtensionMap value) {
        this.extensionMap = value;
    }

    /**
     * Gets the value of the hashUnits property.
     * 
     * @return
     *     possible object is
     *     {@link HashUnits }
     *     
     */
    public HashUnits getHashUnits() {
        return hashUnits;
    }

    /**
     * Sets the value of the hashUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashUnits }
     *     
     */
    public void setHashUnits(HashUnits value) {
        this.hashUnits = value;
    }

}
