//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MassUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MassUnit">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="TONNE"/>
 *     &lt;enumeration value="KILOGRAM"/>
 *     &lt;enumeration value="GRAM"/>
 *     &lt;enumeration value="MILLIGRAM"/>
 *     &lt;enumeration value="STONE"/>
 *     &lt;enumeration value="POUND"/>
 *     &lt;enumeration value="OUNCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MassUnit")
@XmlEnum
public enum MassUnit {

    TONNE,
    KILOGRAM,
    GRAM,
    MILLIGRAM,
    STONE,
    POUND,
    OUNCE;

    public String value() {
        return name();
    }

    public static MassUnit fromValue(String v) {
        return valueOf(v);
    }

}
