//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectCondition.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObjectCondition">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NOT_AVAILABLE"/>
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="AGE_APPROPRIATE"/>
 *     &lt;enumeration value="IN_NEED_OF_REPAIR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ObjectCondition")
@XmlEnum
public enum ObjectCondition {

    NOT_AVAILABLE,
    NEW,
    AGE_APPROPRIATE,
    IN_NEED_OF_REPAIR;

    public String value() {
        return name();
    }

    public static ObjectCondition fromValue(String v) {
        return valueOf(v);
    }

}
