//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PortfolioType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PortfolioType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="INSURANCE"/>
 *     &lt;enumeration value="OPEN_PROPERTY_FUND"/>
 *     &lt;enumeration value="PENSIONS_FUND"/>
 *     &lt;enumeration value="REAL_ESTATE_COMPANIES"/>
 *     &lt;enumeration value="UNLISTED_REAL_ESTATE_COMPANIES"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PortfolioType")
@XmlEnum
public enum PortfolioType {

    INSURANCE,
    OPEN_PROPERTY_FUND,
    PENSIONS_FUND,
    REAL_ESTATE_COMPANIES,
    UNLISTED_REAL_ESTATE_COMPANIES,
    OTHER;

    public String value() {
        return name();
    }

    public static PortfolioType fromValue(String v) {
        return valueOf(v);
    }

}
