//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProjectType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="MAINTENANCE"/>
 *     &lt;enumeration value="INSPECTION"/>
 *     &lt;enumeration value="REPAIR"/>
 *     &lt;enumeration value="OPTIMIZATION"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProjectType")
@XmlEnum
public enum ProjectType {

    NONE,
    MAINTENANCE,
    INSPECTION,
    REPAIR,
    OPTIMIZATION,
    OTHER;

    public String value() {
        return name();
    }

    public static ProjectType fromValue(String v) {
        return valueOf(v);
    }

}
