//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * <p>Java class for Property complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Property">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="administrationCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="airconditioning" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="archValidFrom" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="archValidTo" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="areaMeasurement" type="{}AreaMeasurement" minOccurs="0"/>
 *         &lt;element name="areaType" type="{}AreaType" minOccurs="0"/>
 *         &lt;element name="assetAccountType" type="{}AssetAccountType" minOccurs="0"/>
 *         &lt;element name="assetCategory" type="{}AssetCategory" minOccurs="0"/>
 *         &lt;element name="assetManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="assetValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="balcony" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="barrierfree" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="capitalIncome" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="cellar" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="condition" type="{}ObjectCondition" minOccurs="0"/>
 *         &lt;element name="constructionDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="courtage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="currency" type="{}iTYPE_CURRENCY" minOccurs="0"/>
 *         &lt;element name="distanceToAirport" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="distanceToHighway" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="distanceToPublicTransport" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="distanceToRailStation" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="economicConstructionDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="elevator" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="facilityManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="fairValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="groundRent" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="heatingType" type="{}HeatingType" minOccurs="0"/>
 *         &lt;element name="interiorQuality" type="{}InteriorQuality" minOccurs="0"/>
 *         &lt;element name="ipdObjectId" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="ipdPortfolioId" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="lanCables" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="lastRefurbishmentDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="leasedArea" type="{}Area" minOccurs="0"/>
 *         &lt;element name="locationClassificationType" type="{}LocationType" minOccurs="0"/>
 *         &lt;element name="maintenanceCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="marketRentalValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="modernisationStatus" type="{}RestorationStatus" minOccurs="0"/>
 *         &lt;element name="monumentProtectionCategory" type="{}MonumentsType" minOccurs="0"/>
 *         &lt;element name="netIncome" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="note" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="numberOfBathrooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfBedrooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfCanteen" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfParkingSpaces" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfRooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="operatingCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="operatingCostsSettled" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="optRate" type="{}OptRate" minOccurs="0"/>
 *         &lt;element name="otherCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="ownerOccupation" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="ownershipShare" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="ownershipType" type="{}OwnershipType" minOccurs="0"/>
 *         &lt;element name="partialPurchase" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="partialSales" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="plotArea" type="{}Area" minOccurs="0"/>
 *         &lt;element name="portfolioName" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="portfolioPartName" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="protfolioType" type="{}PortfolioType" minOccurs="0"/>
 *         &lt;element name="propertyManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="purchaseAdditionalCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseBrokerage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="purchaseGrossPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseLegalFees" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseNetPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="purchaseTransferTax" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="rentalIncomeAdditional" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="rentalIncomeMain" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="rented" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="retailLocation" type="{}RetailLocationType" minOccurs="0"/>
 *         &lt;element name="riskStyle" type="{}RiskSegment" minOccurs="0"/>
 *         &lt;element name="saleAdditionalCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="saleBrokerage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="saleDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="saleGrossPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="saleNetPrice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="saleTransferTax" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="titleOfExposee" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="totalApportionableCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="totalGrossCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="totalNetCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="useTypePrimary" type="{}BuildingType" minOccurs="0"/>
 *         &lt;element name="useTypeSecondary" type="{}BuildingType" minOccurs="0"/>
 *         &lt;element name="vacancyOperatingCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="valueIncreasingReconstructCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="address" type="{}Address" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *         &lt;element name="units" type="{}Units" minOccurs="0"/>
 *         &lt;element name="projects" type="{}Projects" minOccurs="0"/>
 *         &lt;element name="lands" type="{}Lands" minOccurs="0"/>
 *         &lt;element name="buildings" type="{}Buildings" minOccurs="0"/>
 *         &lt;element name="leases" type="{}Leases" minOccurs="0"/>
 *         &lt;element name="serviceContracts" type="{}ServiceContracts" minOccurs="0"/>
 *         &lt;element name="valuations" type="{}Valuations" minOccurs="0"/>
 *         &lt;element name="records" type="{}Records" minOccurs="0"/>
 *         &lt;element name="accounts" type="{}Accounts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property", propOrder = {
    "administrationCosts",
    "airconditioning",
    "archValidFrom",
    "archValidTo",
    "areaMeasurement",
    "areaType",
    "assetAccountType",
    "assetCategory",
    "assetManager",
    "assetValue",
    "balcony",
    "barrierfree",
    "capitalIncome",
    "cellar",
    "condition",
    "constructionDate",
    "courtage",
    "currency",
    "distanceToAirport",
    "distanceToHighway",
    "distanceToPublicTransport",
    "distanceToRailStation",
    "economicConstructionDate",
    "elevator",
    "facilityManager",
    "fairValue",
    "groundRent",
    "heatingType",
    "interiorQuality",
    "ipdObjectId",
    "ipdPortfolioId",
    "lanCables",
    "lastRefurbishmentDate",
    "leasedArea",
    "locationClassificationType",
    "maintenanceCosts",
    "marketRentalValue",
    "modernisationStatus",
    "monumentProtectionCategory",
    "netIncome",
    "note",
    "numberOfBathrooms",
    "numberOfBedrooms",
    "numberOfCanteen",
    "numberOfParkingSpaces",
    "numberOfRooms",
    "operatingCosts",
    "operatingCostsSettled",
    "optRate",
    "otherCosts",
    "ownerOccupation",
    "ownershipShare",
    "ownershipType",
    "partialPurchase",
    "partialSales",
    "plotArea",
    "portfolioName",
    "portfolioPartName",
    "protfolioType",
    "propertyManager",
    "purchaseAdditionalCosts",
    "purchaseBrokerage",
    "purchaseDate",
    "purchaseGrossPrice",
    "purchaseLegalFees",
    "purchaseNetPrice",
    "purchaseTransferTax",
    "rentalIncomeAdditional",
    "rentalIncomeMain",
    "rented",
    "retailLocation",
    "riskStyle",
    "saleAdditionalCosts",
    "saleBrokerage",
    "saleDate",
    "saleGrossPrice",
    "saleNetPrice",
    "saleTransferTax",
    "titleOfExposee",
    "totalApportionableCosts",
    "totalGrossCosts",
    "totalNetCosts",
    "useTypePrimary",
    "useTypeSecondary",
    "vacancyOperatingCosts",
    "valueIncreasingReconstructCosts",
    "address",
    "extensionMap",
    "units",
    "projects",
    "lands",
    "buildings",
    "leases",
    "serviceContracts",
    "valuations",
    "records",
    "accounts"
})
public class Property
    extends AbstractEntityNode
{

    protected Amount administrationCosts;
    protected Boolean airconditioning;
    protected String archValidFrom;
    protected String archValidTo;
    @XmlSchemaType(name = "string")
    protected AreaMeasurement areaMeasurement;
    @XmlSchemaType(name = "string")
    protected AreaType areaType;
    @XmlSchemaType(name = "string")
    protected AssetAccountType assetAccountType;
    @XmlSchemaType(name = "string")
    protected AssetCategory assetCategory;
    protected String assetManager;
    protected Amount assetValue;
    protected Boolean balcony;
    protected Boolean barrierfree;
    protected Amount capitalIncome;
    protected Boolean cellar;
    @XmlSchemaType(name = "string")
    protected ObjectCondition condition;
    protected String constructionDate;
    protected Amount courtage;
    protected String currency;
    protected BigDecimal distanceToAirport;
    protected BigDecimal distanceToHighway;
    protected BigDecimal distanceToPublicTransport;
    protected BigDecimal distanceToRailStation;
    protected String economicConstructionDate;
    protected Boolean elevator;
    protected String facilityManager;
    protected Amount fairValue;
    protected Amount groundRent;
    @XmlSchemaType(name = "string")
    protected HeatingType heatingType;
    @XmlSchemaType(name = "string")
    protected InteriorQuality interiorQuality;
    protected String ipdObjectId;
    protected String ipdPortfolioId;
    protected Boolean lanCables;
    protected String lastRefurbishmentDate;
    protected Area leasedArea;
    @XmlSchemaType(name = "string")
    protected LocationType locationClassificationType;
    protected Amount maintenanceCosts;
    protected Amount marketRentalValue;
    @XmlSchemaType(name = "string")
    protected RestorationStatus modernisationStatus;
    @XmlSchemaType(name = "string")
    protected MonumentsType monumentProtectionCategory;
    protected Amount netIncome;
    protected String note;
    protected BigInteger numberOfBathrooms;
    protected BigInteger numberOfBedrooms;
    protected BigInteger numberOfCanteen;
    protected BigInteger numberOfParkingSpaces;
    protected BigInteger numberOfRooms;
    protected Amount operatingCosts;
    protected Amount operatingCostsSettled;
    @XmlSchemaType(name = "string")
    protected OptRate optRate;
    protected Amount otherCosts;
    protected Boolean ownerOccupation;
    protected BigDecimal ownershipShare;
    @XmlSchemaType(name = "string")
    protected OwnershipType ownershipType;
    protected Amount partialPurchase;
    protected Amount partialSales;
    protected Area plotArea;
    protected String portfolioName;
    protected String portfolioPartName;
    @XmlSchemaType(name = "string")
    protected PortfolioType protfolioType;
    protected String propertyManager;
    protected Amount purchaseAdditionalCosts;
    protected Amount purchaseBrokerage;
    protected String purchaseDate;
    protected Amount purchaseGrossPrice;
    protected Amount purchaseLegalFees;
    protected Amount purchaseNetPrice;
    protected Amount purchaseTransferTax;
    protected Amount rentalIncomeAdditional;
    protected Amount rentalIncomeMain;
    protected Boolean rented;
    @XmlSchemaType(name = "string")
    protected RetailLocationType retailLocation;
    @XmlSchemaType(name = "string")
    protected RiskSegment riskStyle;
    protected Amount saleAdditionalCosts;
    protected Amount saleBrokerage;
    protected String saleDate;
    protected Amount saleGrossPrice;
    protected Amount saleNetPrice;
    protected Amount saleTransferTax;
    protected String titleOfExposee;
    protected Amount totalApportionableCosts;
    protected Amount totalGrossCosts;
    protected Amount totalNetCosts;
    @XmlSchemaType(name = "string")
    protected BuildingType useTypePrimary;
    @XmlSchemaType(name = "string")
    protected BuildingType useTypeSecondary;
    protected Amount vacancyOperatingCosts;
    protected Amount valueIncreasingReconstructCosts;
    protected Address address;
    protected ExtensionMap extensionMap;
    protected Units units;
    protected Projects projects;
    protected Lands lands;
    protected Buildings buildings;
    protected Leases leases;
    protected ServiceContracts serviceContracts;
    protected Valuations valuations;
    protected Records records;
    protected Accounts accounts;

    /**
     * Gets the value of the administrationCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAdministrationCosts() {
        return administrationCosts;
    }

    /**
     * Sets the value of the administrationCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAdministrationCosts(Amount value) {
        this.administrationCosts = value;
    }

    /**
     * Gets the value of the airconditioning property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAirconditioning() {
        return airconditioning;
    }

    /**
     * Sets the value of the airconditioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAirconditioning(Boolean value) {
        this.airconditioning = value;
    }

    /**
     * Gets the value of the archValidFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchValidFrom() {
        return archValidFrom;
    }

    /**
     * Sets the value of the archValidFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchValidFrom(String value) {
        this.archValidFrom = value;
    }

    /**
     * Gets the value of the archValidTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchValidTo() {
        return archValidTo;
    }

    /**
     * Sets the value of the archValidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchValidTo(String value) {
        this.archValidTo = value;
    }

    /**
     * Gets the value of the areaMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link AreaMeasurement }
     *     
     */
    public AreaMeasurement getAreaMeasurement() {
        return areaMeasurement;
    }

    /**
     * Sets the value of the areaMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaMeasurement }
     *     
     */
    public void setAreaMeasurement(AreaMeasurement value) {
        this.areaMeasurement = value;
    }

    /**
     * Gets the value of the areaType property.
     * 
     * @return
     *     possible object is
     *     {@link AreaType }
     *     
     */
    public AreaType getAreaType() {
        return areaType;
    }

    /**
     * Sets the value of the areaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaType }
     *     
     */
    public void setAreaType(AreaType value) {
        this.areaType = value;
    }

    /**
     * Gets the value of the assetAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link AssetAccountType }
     *     
     */
    public AssetAccountType getAssetAccountType() {
        return assetAccountType;
    }

    /**
     * Sets the value of the assetAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetAccountType }
     *     
     */
    public void setAssetAccountType(AssetAccountType value) {
        this.assetAccountType = value;
    }

    /**
     * Gets the value of the assetCategory property.
     * 
     * @return
     *     possible object is
     *     {@link AssetCategory }
     *     
     */
    public AssetCategory getAssetCategory() {
        return assetCategory;
    }

    /**
     * Sets the value of the assetCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetCategory }
     *     
     */
    public void setAssetCategory(AssetCategory value) {
        this.assetCategory = value;
    }

    /**
     * Gets the value of the assetManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetManager() {
        return assetManager;
    }

    /**
     * Sets the value of the assetManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetManager(String value) {
        this.assetManager = value;
    }

    /**
     * Gets the value of the assetValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAssetValue() {
        return assetValue;
    }

    /**
     * Sets the value of the assetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAssetValue(Amount value) {
        this.assetValue = value;
    }

    /**
     * Gets the value of the balcony property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBalcony() {
        return balcony;
    }

    /**
     * Sets the value of the balcony property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBalcony(Boolean value) {
        this.balcony = value;
    }

    /**
     * Gets the value of the barrierfree property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBarrierfree() {
        return barrierfree;
    }

    /**
     * Sets the value of the barrierfree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBarrierfree(Boolean value) {
        this.barrierfree = value;
    }

    /**
     * Gets the value of the capitalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getCapitalIncome() {
        return capitalIncome;
    }

    /**
     * Sets the value of the capitalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setCapitalIncome(Amount value) {
        this.capitalIncome = value;
    }

    /**
     * Gets the value of the cellar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCellar() {
        return cellar;
    }

    /**
     * Sets the value of the cellar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCellar(Boolean value) {
        this.cellar = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectCondition }
     *     
     */
    public ObjectCondition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectCondition }
     *     
     */
    public void setCondition(ObjectCondition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the constructionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstructionDate() {
        return constructionDate;
    }

    /**
     * Sets the value of the constructionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstructionDate(String value) {
        this.constructionDate = value;
    }

    /**
     * Gets the value of the courtage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getCourtage() {
        return courtage;
    }

    /**
     * Sets the value of the courtage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setCourtage(Amount value) {
        this.courtage = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the distanceToAirport property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistanceToAirport() {
        return distanceToAirport;
    }

    /**
     * Sets the value of the distanceToAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistanceToAirport(BigDecimal value) {
        this.distanceToAirport = value;
    }

    /**
     * Gets the value of the distanceToHighway property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistanceToHighway() {
        return distanceToHighway;
    }

    /**
     * Sets the value of the distanceToHighway property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistanceToHighway(BigDecimal value) {
        this.distanceToHighway = value;
    }

    /**
     * Gets the value of the distanceToPublicTransport property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistanceToPublicTransport() {
        return distanceToPublicTransport;
    }

    /**
     * Sets the value of the distanceToPublicTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistanceToPublicTransport(BigDecimal value) {
        this.distanceToPublicTransport = value;
    }

    /**
     * Gets the value of the distanceToRailStation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDistanceToRailStation() {
        return distanceToRailStation;
    }

    /**
     * Sets the value of the distanceToRailStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDistanceToRailStation(BigDecimal value) {
        this.distanceToRailStation = value;
    }

    /**
     * Gets the value of the economicConstructionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEconomicConstructionDate() {
        return economicConstructionDate;
    }

    /**
     * Sets the value of the economicConstructionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEconomicConstructionDate(String value) {
        this.economicConstructionDate = value;
    }

    /**
     * Gets the value of the elevator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isElevator() {
        return elevator;
    }

    /**
     * Sets the value of the elevator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setElevator(Boolean value) {
        this.elevator = value;
    }

    /**
     * Gets the value of the facilityManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityManager() {
        return facilityManager;
    }

    /**
     * Sets the value of the facilityManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityManager(String value) {
        this.facilityManager = value;
    }

    /**
     * Gets the value of the fairValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getFairValue() {
        return fairValue;
    }

    /**
     * Sets the value of the fairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setFairValue(Amount value) {
        this.fairValue = value;
    }

    /**
     * Gets the value of the groundRent property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getGroundRent() {
        return groundRent;
    }

    /**
     * Sets the value of the groundRent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setGroundRent(Amount value) {
        this.groundRent = value;
    }

    /**
     * Gets the value of the heatingType property.
     * 
     * @return
     *     possible object is
     *     {@link HeatingType }
     *     
     */
    public HeatingType getHeatingType() {
        return heatingType;
    }

    /**
     * Sets the value of the heatingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeatingType }
     *     
     */
    public void setHeatingType(HeatingType value) {
        this.heatingType = value;
    }

    /**
     * Gets the value of the interiorQuality property.
     * 
     * @return
     *     possible object is
     *     {@link InteriorQuality }
     *     
     */
    public InteriorQuality getInteriorQuality() {
        return interiorQuality;
    }

    /**
     * Sets the value of the interiorQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteriorQuality }
     *     
     */
    public void setInteriorQuality(InteriorQuality value) {
        this.interiorQuality = value;
    }

    /**
     * Gets the value of the ipdObjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdObjectId() {
        return ipdObjectId;
    }

    /**
     * Sets the value of the ipdObjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdObjectId(String value) {
        this.ipdObjectId = value;
    }

    /**
     * Gets the value of the ipdPortfolioId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpdPortfolioId() {
        return ipdPortfolioId;
    }

    /**
     * Sets the value of the ipdPortfolioId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpdPortfolioId(String value) {
        this.ipdPortfolioId = value;
    }

    /**
     * Gets the value of the lanCables property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLanCables() {
        return lanCables;
    }

    /**
     * Sets the value of the lanCables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLanCables(Boolean value) {
        this.lanCables = value;
    }

    /**
     * Gets the value of the lastRefurbishmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastRefurbishmentDate() {
        return lastRefurbishmentDate;
    }

    /**
     * Sets the value of the lastRefurbishmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastRefurbishmentDate(String value) {
        this.lastRefurbishmentDate = value;
    }

    /**
     * Gets the value of the leasedArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getLeasedArea() {
        return leasedArea;
    }

    /**
     * Sets the value of the leasedArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setLeasedArea(Area value) {
        this.leasedArea = value;
    }

    /**
     * Gets the value of the locationClassificationType property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocationClassificationType() {
        return locationClassificationType;
    }

    /**
     * Sets the value of the locationClassificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocationClassificationType(LocationType value) {
        this.locationClassificationType = value;
    }

    /**
     * Gets the value of the maintenanceCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getMaintenanceCosts() {
        return maintenanceCosts;
    }

    /**
     * Sets the value of the maintenanceCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setMaintenanceCosts(Amount value) {
        this.maintenanceCosts = value;
    }

    /**
     * Gets the value of the marketRentalValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getMarketRentalValue() {
        return marketRentalValue;
    }

    /**
     * Sets the value of the marketRentalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setMarketRentalValue(Amount value) {
        this.marketRentalValue = value;
    }

    /**
     * Gets the value of the modernisationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RestorationStatus }
     *     
     */
    public RestorationStatus getModernisationStatus() {
        return modernisationStatus;
    }

    /**
     * Sets the value of the modernisationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestorationStatus }
     *     
     */
    public void setModernisationStatus(RestorationStatus value) {
        this.modernisationStatus = value;
    }

    /**
     * Gets the value of the monumentProtectionCategory property.
     * 
     * @return
     *     possible object is
     *     {@link MonumentsType }
     *     
     */
    public MonumentsType getMonumentProtectionCategory() {
        return monumentProtectionCategory;
    }

    /**
     * Sets the value of the monumentProtectionCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonumentsType }
     *     
     */
    public void setMonumentProtectionCategory(MonumentsType value) {
        this.monumentProtectionCategory = value;
    }

    /**
     * Gets the value of the netIncome property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getNetIncome() {
        return netIncome;
    }

    /**
     * Sets the value of the netIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setNetIncome(Amount value) {
        this.netIncome = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the numberOfBathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBathrooms() {
        return numberOfBathrooms;
    }

    /**
     * Sets the value of the numberOfBathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBathrooms(BigInteger value) {
        this.numberOfBathrooms = value;
    }

    /**
     * Gets the value of the numberOfBedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBedrooms() {
        return numberOfBedrooms;
    }

    /**
     * Sets the value of the numberOfBedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBedrooms(BigInteger value) {
        this.numberOfBedrooms = value;
    }

    /**
     * Gets the value of the numberOfCanteen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfCanteen() {
        return numberOfCanteen;
    }

    /**
     * Sets the value of the numberOfCanteen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfCanteen(BigInteger value) {
        this.numberOfCanteen = value;
    }

    /**
     * Gets the value of the numberOfParkingSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfParkingSpaces() {
        return numberOfParkingSpaces;
    }

    /**
     * Sets the value of the numberOfParkingSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfParkingSpaces(BigInteger value) {
        this.numberOfParkingSpaces = value;
    }

    /**
     * Gets the value of the numberOfRooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfRooms() {
        return numberOfRooms;
    }

    /**
     * Sets the value of the numberOfRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfRooms(BigInteger value) {
        this.numberOfRooms = value;
    }

    /**
     * Gets the value of the operatingCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOperatingCosts() {
        return operatingCosts;
    }

    /**
     * Sets the value of the operatingCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOperatingCosts(Amount value) {
        this.operatingCosts = value;
    }

    /**
     * Gets the value of the operatingCostsSettled property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOperatingCostsSettled() {
        return operatingCostsSettled;
    }

    /**
     * Sets the value of the operatingCostsSettled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOperatingCostsSettled(Amount value) {
        this.operatingCostsSettled = value;
    }

    /**
     * Gets the value of the optRate property.
     * 
     * @return
     *     possible object is
     *     {@link OptRate }
     *     
     */
    public OptRate getOptRate() {
        return optRate;
    }

    /**
     * Sets the value of the optRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptRate }
     *     
     */
    public void setOptRate(OptRate value) {
        this.optRate = value;
    }

    /**
     * Gets the value of the otherCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOtherCosts() {
        return otherCosts;
    }

    /**
     * Sets the value of the otherCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOtherCosts(Amount value) {
        this.otherCosts = value;
    }

    /**
     * Gets the value of the ownerOccupation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOwnerOccupation() {
        return ownerOccupation;
    }

    /**
     * Sets the value of the ownerOccupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwnerOccupation(Boolean value) {
        this.ownerOccupation = value;
    }

    /**
     * Gets the value of the ownershipShare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOwnershipShare() {
        return ownershipShare;
    }

    /**
     * Sets the value of the ownershipShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOwnershipShare(BigDecimal value) {
        this.ownershipShare = value;
    }

    /**
     * Gets the value of the ownershipType property.
     * 
     * @return
     *     possible object is
     *     {@link OwnershipType }
     *     
     */
    public OwnershipType getOwnershipType() {
        return ownershipType;
    }

    /**
     * Sets the value of the ownershipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnershipType }
     *     
     */
    public void setOwnershipType(OwnershipType value) {
        this.ownershipType = value;
    }

    /**
     * Gets the value of the partialPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPartialPurchase() {
        return partialPurchase;
    }

    /**
     * Sets the value of the partialPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPartialPurchase(Amount value) {
        this.partialPurchase = value;
    }

    /**
     * Gets the value of the partialSales property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPartialSales() {
        return partialSales;
    }

    /**
     * Sets the value of the partialSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPartialSales(Amount value) {
        this.partialSales = value;
    }

    /**
     * Gets the value of the plotArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getPlotArea() {
        return plotArea;
    }

    /**
     * Sets the value of the plotArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setPlotArea(Area value) {
        this.plotArea = value;
    }

    /**
     * Gets the value of the portfolioName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioName() {
        return portfolioName;
    }

    /**
     * Sets the value of the portfolioName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioName(String value) {
        this.portfolioName = value;
    }

    /**
     * Gets the value of the portfolioPartName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioPartName() {
        return portfolioPartName;
    }

    /**
     * Sets the value of the portfolioPartName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioPartName(String value) {
        this.portfolioPartName = value;
    }

    /**
     * Gets the value of the protfolioType property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioType }
     *     
     */
    public PortfolioType getProtfolioType() {
        return protfolioType;
    }

    /**
     * Sets the value of the protfolioType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioType }
     *     
     */
    public void setProtfolioType(PortfolioType value) {
        this.protfolioType = value;
    }

    /**
     * Gets the value of the propertyManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyManager() {
        return propertyManager;
    }

    /**
     * Sets the value of the propertyManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyManager(String value) {
        this.propertyManager = value;
    }

    /**
     * Gets the value of the purchaseAdditionalCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseAdditionalCosts() {
        return purchaseAdditionalCosts;
    }

    /**
     * Sets the value of the purchaseAdditionalCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseAdditionalCosts(Amount value) {
        this.purchaseAdditionalCosts = value;
    }

    /**
     * Gets the value of the purchaseBrokerage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseBrokerage() {
        return purchaseBrokerage;
    }

    /**
     * Sets the value of the purchaseBrokerage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseBrokerage(Amount value) {
        this.purchaseBrokerage = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDate(String value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the purchaseGrossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseGrossPrice() {
        return purchaseGrossPrice;
    }

    /**
     * Sets the value of the purchaseGrossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseGrossPrice(Amount value) {
        this.purchaseGrossPrice = value;
    }

    /**
     * Gets the value of the purchaseLegalFees property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseLegalFees() {
        return purchaseLegalFees;
    }

    /**
     * Sets the value of the purchaseLegalFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseLegalFees(Amount value) {
        this.purchaseLegalFees = value;
    }

    /**
     * Gets the value of the purchaseNetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseNetPrice() {
        return purchaseNetPrice;
    }

    /**
     * Sets the value of the purchaseNetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseNetPrice(Amount value) {
        this.purchaseNetPrice = value;
    }

    /**
     * Gets the value of the purchaseTransferTax property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPurchaseTransferTax() {
        return purchaseTransferTax;
    }

    /**
     * Sets the value of the purchaseTransferTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPurchaseTransferTax(Amount value) {
        this.purchaseTransferTax = value;
    }

    /**
     * Gets the value of the rentalIncomeAdditional property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getRentalIncomeAdditional() {
        return rentalIncomeAdditional;
    }

    /**
     * Sets the value of the rentalIncomeAdditional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setRentalIncomeAdditional(Amount value) {
        this.rentalIncomeAdditional = value;
    }

    /**
     * Gets the value of the rentalIncomeMain property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getRentalIncomeMain() {
        return rentalIncomeMain;
    }

    /**
     * Sets the value of the rentalIncomeMain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setRentalIncomeMain(Amount value) {
        this.rentalIncomeMain = value;
    }

    /**
     * Gets the value of the rented property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRented() {
        return rented;
    }

    /**
     * Sets the value of the rented property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRented(Boolean value) {
        this.rented = value;
    }

    /**
     * Gets the value of the retailLocation property.
     * 
     * @return
     *     possible object is
     *     {@link RetailLocationType }
     *     
     */
    public RetailLocationType getRetailLocation() {
        return retailLocation;
    }

    /**
     * Sets the value of the retailLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetailLocationType }
     *     
     */
    public void setRetailLocation(RetailLocationType value) {
        this.retailLocation = value;
    }

    /**
     * Gets the value of the riskStyle property.
     * 
     * @return
     *     possible object is
     *     {@link RiskSegment }
     *     
     */
    public RiskSegment getRiskStyle() {
        return riskStyle;
    }

    /**
     * Sets the value of the riskStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskSegment }
     *     
     */
    public void setRiskStyle(RiskSegment value) {
        this.riskStyle = value;
    }

    /**
     * Gets the value of the saleAdditionalCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleAdditionalCosts() {
        return saleAdditionalCosts;
    }

    /**
     * Sets the value of the saleAdditionalCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleAdditionalCosts(Amount value) {
        this.saleAdditionalCosts = value;
    }

    /**
     * Gets the value of the saleBrokerage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleBrokerage() {
        return saleBrokerage;
    }

    /**
     * Sets the value of the saleBrokerage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleBrokerage(Amount value) {
        this.saleBrokerage = value;
    }

    /**
     * Gets the value of the saleDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleDate() {
        return saleDate;
    }

    /**
     * Sets the value of the saleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleDate(String value) {
        this.saleDate = value;
    }

    /**
     * Gets the value of the saleGrossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleGrossPrice() {
        return saleGrossPrice;
    }

    /**
     * Sets the value of the saleGrossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleGrossPrice(Amount value) {
        this.saleGrossPrice = value;
    }

    /**
     * Gets the value of the saleNetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleNetPrice() {
        return saleNetPrice;
    }

    /**
     * Sets the value of the saleNetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleNetPrice(Amount value) {
        this.saleNetPrice = value;
    }

    /**
     * Gets the value of the saleTransferTax property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSaleTransferTax() {
        return saleTransferTax;
    }

    /**
     * Sets the value of the saleTransferTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSaleTransferTax(Amount value) {
        this.saleTransferTax = value;
    }

    /**
     * Gets the value of the titleOfExposee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleOfExposee() {
        return titleOfExposee;
    }

    /**
     * Sets the value of the titleOfExposee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleOfExposee(String value) {
        this.titleOfExposee = value;
    }

    /**
     * Gets the value of the totalApportionableCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTotalApportionableCosts() {
        return totalApportionableCosts;
    }

    /**
     * Sets the value of the totalApportionableCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTotalApportionableCosts(Amount value) {
        this.totalApportionableCosts = value;
    }

    /**
     * Gets the value of the totalGrossCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTotalGrossCosts() {
        return totalGrossCosts;
    }

    /**
     * Sets the value of the totalGrossCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTotalGrossCosts(Amount value) {
        this.totalGrossCosts = value;
    }

    /**
     * Gets the value of the totalNetCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTotalNetCosts() {
        return totalNetCosts;
    }

    /**
     * Sets the value of the totalNetCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTotalNetCosts(Amount value) {
        this.totalNetCosts = value;
    }

    /**
     * Gets the value of the useTypePrimary property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingType }
     *     
     */
    public BuildingType getUseTypePrimary() {
        return useTypePrimary;
    }

    /**
     * Sets the value of the useTypePrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingType }
     *     
     */
    public void setUseTypePrimary(BuildingType value) {
        this.useTypePrimary = value;
    }

    /**
     * Gets the value of the useTypeSecondary property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingType }
     *     
     */
    public BuildingType getUseTypeSecondary() {
        return useTypeSecondary;
    }

    /**
     * Sets the value of the useTypeSecondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingType }
     *     
     */
    public void setUseTypeSecondary(BuildingType value) {
        this.useTypeSecondary = value;
    }

    /**
     * Gets the value of the vacancyOperatingCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getVacancyOperatingCosts() {
        return vacancyOperatingCosts;
    }

    /**
     * Sets the value of the vacancyOperatingCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setVacancyOperatingCosts(Amount value) {
        this.vacancyOperatingCosts = value;
    }

    /**
     * Gets the value of the valueIncreasingReconstructCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getValueIncreasingReconstructCosts() {
        return valueIncreasingReconstructCosts;
    }

    /**
     * Sets the value of the valueIncreasingReconstructCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setValueIncreasingReconstructCosts(Amount value) {
        this.valueIncreasingReconstructCosts = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the extensionMap property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionMap }
     *     
     */
    public ExtensionMap getExtensionMap() {
        return extensionMap;
    }

    /**
     * Sets the value of the extensionMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionMap }
     *     
     */
    public void setExtensionMap(ExtensionMap value) {
        this.extensionMap = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Units }
     *     
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Units }
     *     
     */
    public void setUnits(Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link Projects }
     *     
     */
    public Projects getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Projects }
     *     
     */
    public void setProjects(Projects value) {
        this.projects = value;
    }

    /**
     * Gets the value of the lands property.
     * 
     * @return
     *     possible object is
     *     {@link Lands }
     *     
     */
    public Lands getLands() {
        return lands;
    }

    /**
     * Sets the value of the lands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lands }
     *     
     */
    public void setLands(Lands value) {
        this.lands = value;
    }

    /**
     * Gets the value of the buildings property.
     * 
     * @return
     *     possible object is
     *     {@link Buildings }
     *     
     */
    public Buildings getBuildings() {
        return buildings;
    }

    /**
     * Sets the value of the buildings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Buildings }
     *     
     */
    public void setBuildings(Buildings value) {
        this.buildings = value;
    }

    /**
     * Gets the value of the leases property.
     * 
     * @return
     *     possible object is
     *     {@link Leases }
     *     
     */
    public Leases getLeases() {
        return leases;
    }

    /**
     * Sets the value of the leases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leases }
     *     
     */
    public void setLeases(Leases value) {
        this.leases = value;
    }

    /**
     * Gets the value of the serviceContracts property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceContracts }
     *     
     */
    public ServiceContracts getServiceContracts() {
        return serviceContracts;
    }

    /**
     * Sets the value of the serviceContracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceContracts }
     *     
     */
    public void setServiceContracts(ServiceContracts value) {
        this.serviceContracts = value;
    }

    /**
     * Gets the value of the valuations property.
     * 
     * @return
     *     possible object is
     *     {@link Valuations }
     *     
     */
    public Valuations getValuations() {
        return valuations;
    }

    /**
     * Sets the value of the valuations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Valuations }
     *     
     */
    public void setValuations(Valuations value) {
        this.valuations = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link Records }
     *     
     */
    public Records getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link Records }
     *     
     */
    public void setRecords(Records value) {
        this.records = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link Accounts }
     *     
     */
    public Accounts getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accounts }
     *     
     */
    public void setAccounts(Accounts value) {
        this.accounts = value;
    }

}
