//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RestorationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RestorationStatus">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NOT_AVAILABLE"/>
 *     &lt;enumeration value="FULLY_REFURBISHED"/>
 *     &lt;enumeration value="PARTLY_REFURBISHED"/>
 *     &lt;enumeration value="NOT_REFURBISHED"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RestorationStatus")
@XmlEnum
public enum RestorationStatus {

    NOT_AVAILABLE,
    FULLY_REFURBISHED,
    PARTLY_REFURBISHED,
    NOT_REFURBISHED,
    OTHER;

    public String value() {
        return name();
    }

    public static RestorationStatus fromValue(String v) {
        return valueOf(v);
    }

}
