//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import java.math.BigInteger;


/**
 * <p>Java class for ServiceContract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceContract">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="contractCompletionDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="contractExtensionDuration" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="contractOption" type="{}ContractOption" minOccurs="0"/>
 *         &lt;element name="creditor" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="firstPaymentDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="netAmountPerPayment" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="paymentPattern" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="paymentsPerYear" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="serviceType" type="{}ServiceType" minOccurs="0"/>
 *         &lt;element name="specifications" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="terminated" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="terminationLegitDeadline" type="{}LegitTerminationDeadline" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceContract", propOrder = {
    "contractCompletionDate",
    "contractExtensionDuration",
    "contractOption",
    "creditor",
    "firstPaymentDate",
    "netAmountPerPayment",
    "paymentPattern",
    "paymentsPerYear",
    "serviceType",
    "specifications",
    "terminated",
    "terminationLegitDeadline",
    "extensionMap"
})
public class ServiceContract
    extends AbstractEntityNode
{

    protected String contractCompletionDate;
    protected Duration contractExtensionDuration;
    @XmlSchemaType(name = "string")
    protected ContractOption contractOption;
    protected String creditor;
    protected String firstPaymentDate;
    protected Amount netAmountPerPayment;
    protected Duration paymentPattern;
    protected BigInteger paymentsPerYear;
    @XmlSchemaType(name = "string")
    protected ServiceType serviceType;
    protected String specifications;
    protected Boolean terminated;
    @XmlSchemaType(name = "string")
    protected LegitTerminationDeadline terminationLegitDeadline;
    protected ExtensionMap extensionMap;

    /**
     * Gets the value of the contractCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractCompletionDate() {
        return contractCompletionDate;
    }

    /**
     * Sets the value of the contractCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractCompletionDate(String value) {
        this.contractCompletionDate = value;
    }

    /**
     * Gets the value of the contractExtensionDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getContractExtensionDuration() {
        return contractExtensionDuration;
    }

    /**
     * Sets the value of the contractExtensionDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setContractExtensionDuration(Duration value) {
        this.contractExtensionDuration = value;
    }

    /**
     * Gets the value of the contractOption property.
     * 
     * @return
     *     possible object is
     *     {@link ContractOption }
     *     
     */
    public ContractOption getContractOption() {
        return contractOption;
    }

    /**
     * Sets the value of the contractOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractOption }
     *     
     */
    public void setContractOption(ContractOption value) {
        this.contractOption = value;
    }

    /**
     * Gets the value of the creditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditor() {
        return creditor;
    }

    /**
     * Sets the value of the creditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditor(String value) {
        this.creditor = value;
    }

    /**
     * Gets the value of the firstPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPaymentDate() {
        return firstPaymentDate;
    }

    /**
     * Sets the value of the firstPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPaymentDate(String value) {
        this.firstPaymentDate = value;
    }

    /**
     * Gets the value of the netAmountPerPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getNetAmountPerPayment() {
        return netAmountPerPayment;
    }

    /**
     * Sets the value of the netAmountPerPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setNetAmountPerPayment(Amount value) {
        this.netAmountPerPayment = value;
    }

    /**
     * Gets the value of the paymentPattern property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPaymentPattern() {
        return paymentPattern;
    }

    /**
     * Sets the value of the paymentPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPaymentPattern(Duration value) {
        this.paymentPattern = value;
    }

    /**
     * Gets the value of the paymentsPerYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPaymentsPerYear() {
        return paymentsPerYear;
    }

    /**
     * Sets the value of the paymentsPerYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPaymentsPerYear(BigInteger value) {
        this.paymentsPerYear = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setServiceType(ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the specifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * Sets the value of the specifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifications(String value) {
        this.specifications = value;
    }

    /**
     * Gets the value of the terminated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTerminated() {
        return terminated;
    }

    /**
     * Sets the value of the terminated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTerminated(Boolean value) {
        this.terminated = value;
    }

    /**
     * Gets the value of the terminationLegitDeadline property.
     * 
     * @return
     *     possible object is
     *     {@link LegitTerminationDeadline }
     *     
     */
    public LegitTerminationDeadline getTerminationLegitDeadline() {
        return terminationLegitDeadline;
    }

    /**
     * Sets the value of the terminationLegitDeadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegitTerminationDeadline }
     *     
     */
    public void setTerminationLegitDeadline(LegitTerminationDeadline value) {
        this.terminationLegitDeadline = value;
    }

    /**
     * Gets the value of the extensionMap property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionMap }
     *     
     */
    public ExtensionMap getExtensionMap() {
        return extensionMap;
    }

    /**
     * Sets the value of the extensionMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionMap }
     *     
     */
    public void setExtensionMap(ExtensionMap value) {
        this.extensionMap = value;
    }

}
