//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 12:41:56 PM CEST 
//


package org.zgif.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ZGif complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZGif">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractNode">
 *       &lt;sequence>
 *         &lt;element name="manifest" type="{}Manifest"/>
 *         &lt;element name="periods" type="{}Periods"/>
 *         &lt;element name="meta" type="{}Meta"/>
 *         &lt;element name="maindata" type="{}Data"/>
 *       &lt;/sequence>
 *       &lt;attribute name="filePath" type="{}iTYPE_STRING" />
 *       &lt;attribute name="mimetype" type="{}iTYPE_STRING" />
 *       &lt;attribute name="type" type="{}iTYPE_STRING" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZGif", propOrder = {
    "manifest",
    "periods",
    "meta",
    "maindata"
})
public class ZGif
    extends AbstractNode
{

    @XmlElement(required = true)
    protected Manifest manifest;
    @XmlElement(required = true)
    protected Periods periods;
    @XmlElement(required = true)
    protected Meta meta;
    @XmlElement(required = true)
    protected Data maindata;
    @XmlAttribute(name = "filePath")
    protected String filePath;
    @XmlAttribute(name = "mimetype")
    protected String mimetype;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the manifest property.
     * 
     * @return
     *     possible object is
     *     {@link Manifest }
     *     
     */
    public Manifest getManifest() {
        return manifest;
    }

    /**
     * Sets the value of the manifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manifest }
     *     
     */
    public void setManifest(Manifest value) {
        this.manifest = value;
    }

    /**
     * Gets the value of the periods property.
     * 
     * @return
     *     possible object is
     *     {@link Periods }
     *     
     */
    public Periods getPeriods() {
        return periods;
    }

    /**
     * Sets the value of the periods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periods }
     *     
     */
    public void setPeriods(Periods value) {
        this.periods = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the maindata property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getMaindata() {
        return maindata;
    }

    /**
     * Sets the value of the maindata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setMaindata(Data value) {
        this.maindata = value;
    }

    /**
     * Gets the value of the filePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Sets the value of the filePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilePath(String value) {
        this.filePath = value;
    }

    /**
     * Gets the value of the mimetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimetype() {
        return mimetype;
    }

    /**
     * Sets the value of the mimetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimetype(String value) {
        this.mimetype = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
