package org.zgif.model.node.entity;

import org.zgif.model.datatype.Amount;
import org.zgif.model.datatype.enumeration.AccountingStandard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.16 at 03:29:57 PM CEST
//


/**
 * <p>Java class for Account complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="accountingStandard" type="{}AccountingStandard" minOccurs="0"/>
 *         &lt;element name="balancePosition" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="value" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="records" type="{}Records" minOccurs="0"/>
 *         &lt;element name="bookEntries" type="{}BookEntries" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account", propOrder = {
    "accountingStandard",
    "balancePosition",
    "value",
    "records",
    "bookEntries"
})
public class Account
    extends AbstractEntityNode
{

    protected AccountingStandard accountingStandard;
    protected String balancePosition;
    protected Amount value;
    protected Records records;
    protected BookEntries bookEntries;

    /**
     * Gets the value of the accountingStandard property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingStandard }
     *     
     */
    public AccountingStandard getAccountingStandard() {
        return accountingStandard;
    }

    /**
     * Sets the value of the accountingStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingStandard }
     *     
     */
    public void setAccountingStandard(AccountingStandard value) {
        this.accountingStandard = value;
    }

    /**
     * Gets the value of the balancePosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalancePosition() {
        return balancePosition;
    }

    /**
     * Sets the value of the balancePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalancePosition(String value) {
        this.balancePosition = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setValue(Amount value) {
        this.value = value;
    }

    /**
     * Gets the value of the records property.
     * 
     * @return
     *     possible object is
     *     {@link Records }
     *     
     */
    public Records getRecords() {
        return records;
    }

    /**
     * Sets the value of the records property.
     * 
     * @param value
     *     allowed object is
     *     {@link Records }
     *     
     */
    public void setRecords(Records value) {
        this.records = value;
    }

    /**
     * Gets the value of the bookEntries property.
     * 
     * @return
     *     possible object is
     *     {@link BookEntries }
     *     
     */
    public BookEntries getBookEntries() {
        return bookEntries;
    }

    /**
     * Sets the value of the bookEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookEntries }
     *     
     */
    public void setBookEntries(BookEntries value) {
        this.bookEntries = value;
    }

}
