package org.zgif.model.node.entity;

import org.zgif.model.datatype.Amount;
import org.zgif.model.datatype.enumeration.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import java.math.BigInteger;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.16 at 03:29:57 PM CEST
//


/**
 * <p>Java class for Lease complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lease">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="acceptedTerminationDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="badDebt" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="beginRentPayment" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="breakOption" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="collectiveObjectIdSender" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="contractCompletionDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="contractExtensionDuration" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="courtage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="currency" type="{}iTYPE_CURRENCY" minOccurs="0"/>
 *         &lt;element name="debitor" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="debitorId" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="depositAgreed" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="depositAmount" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="depositIncreaseType" type="{}DepositIncreaseType" minOccurs="0"/>
 *         &lt;element name="depositPayed" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="depositType" type="{}DepositType" minOccurs="0"/>
 *         &lt;element name="dmiendOption" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="dunningIndicator" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="dunningLevel" type="{}DunningLevel" minOccurs="0"/>
 *         &lt;element name="freeFrom" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="heatingCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="leaseBeginDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="leaseContractType" type="{}LeaseContractType" minOccurs="0"/>
 *         &lt;element name="leaseEndDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="maxNumberOfPerson" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="maxRentalTime" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="minRentalTime" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="nation" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="openItems" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="operatingCostPrepayment" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="operatingCostsSettled" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="option" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="parkingSpaceCosts" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="payment" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="paymentPattern" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="periodsTurnoverRents" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="petsAllowed" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="propertyManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="sector" type="{}Sector" minOccurs="0"/>
 *         &lt;element name="tenancy" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="terminated" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="terminationDuration" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="terminationReceiptDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="turnoverAdjType" type="{}NumberType" minOccurs="0"/>
 *         &lt;element name="turnoverCertificate" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="turnoverMinimum" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="turnoverRentCap" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="turnoverReportingInterval" type="{}iTYPE_PERIOD" minOccurs="0"/>
 *         &lt;element name="turnoverSortiment" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *         &lt;element name="termUnits" type="{}TermUnits" minOccurs="0"/>
 *         &lt;element name="terms" type="{}Terms" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lease", propOrder = {
    "acceptedTerminationDate",
    "badDebt",
    "beginRentPayment",
    "breakOption",
    "collectiveObjectIdSender",
    "contractCompletionDate",
    "contractExtensionDuration",
    "courtage",
    "currency",
    "debitor",
    "debitorId",
    "depositAgreed",
    "depositAmount",
    "depositIncreaseType",
    "depositPayed",
    "depositType",
    "dmiendOption",
    "dunningIndicator",
    "dunningLevel",
    "freeFrom",
    "heatingCosts",
    "leaseBeginDate",
    "leaseContractType",
    "leaseEndDate",
    "maxNumberOfPerson",
    "maxRentalTime",
    "minRentalTime",
    "nation",
    "openItems",
    "operatingCostPrepayment",
    "operatingCostsSettled",
    "option",
    "parkingSpaceCosts",
    "payment",
    "paymentPattern",
    "periodsTurnoverRents",
    "petsAllowed",
    "propertyManager",
    "sector",
    "tenancy",
    "terminated",
    "terminationDuration",
    "terminationReceiptDate",
    "turnoverAdjType",
    "turnoverCertificate",
    "turnoverMinimum",
    "turnoverRentCap",
    "turnoverReportingInterval",
    "turnoverSortiment",
    "extensionMap",
    "termUnits",
    "terms"
})
public class Lease
    extends AbstractEntityNode
{

    protected String acceptedTerminationDate;
    protected Amount badDebt;
    protected String beginRentPayment;
    protected String breakOption;
    protected String collectiveObjectIdSender;
    protected String contractCompletionDate;
    protected Duration contractExtensionDuration;
    protected Amount courtage;
    protected String currency;
    protected String debitor;
    protected String debitorId;
    protected Boolean depositAgreed;
    protected Amount depositAmount;
    protected DepositIncreaseType depositIncreaseType;
    protected Boolean depositPayed;
    protected DepositType depositType;
    protected String dmiendOption;
    protected Boolean dunningIndicator;
    protected DunningLevel dunningLevel;
    protected String freeFrom;
    protected Amount heatingCosts;
    protected String leaseBeginDate;
    protected LeaseContractType leaseContractType;
    protected String leaseEndDate;
    protected BigInteger maxNumberOfPerson;
    protected Duration maxRentalTime;
    protected Duration minRentalTime;
    protected String nation;
    protected Amount openItems;
    protected Amount operatingCostPrepayment;
    protected Amount operatingCostsSettled;
    protected Boolean option;
    protected Amount parkingSpaceCosts;
    protected Amount payment;
    protected Duration paymentPattern;
    protected Duration periodsTurnoverRents;
    protected Boolean petsAllowed;
    protected String propertyManager;
    protected Sector sector;
    protected Duration tenancy;
    protected Boolean terminated;
    protected Duration terminationDuration;
    protected String terminationReceiptDate;
    protected NumberType turnoverAdjType;
    protected Boolean turnoverCertificate;
    protected Amount turnoverMinimum;
    protected Amount turnoverRentCap;
    protected Duration turnoverReportingInterval;
    protected String turnoverSortiment;
    protected TermUnits termUnits;
    protected Terms terms;

    /**
     * Gets the value of the acceptedTerminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptedTerminationDate() {
        return acceptedTerminationDate;
    }

    /**
     * Sets the value of the acceptedTerminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptedTerminationDate(String value) {
        this.acceptedTerminationDate = value;
    }

    /**
     * Gets the value of the badDebt property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getBadDebt() {
        return badDebt;
    }

    /**
     * Sets the value of the badDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setBadDebt(Amount value) {
        this.badDebt = value;
    }

    /**
     * Gets the value of the beginRentPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeginRentPayment() {
        return beginRentPayment;
    }

    /**
     * Sets the value of the beginRentPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeginRentPayment(String value) {
        this.beginRentPayment = value;
    }

    /**
     * Gets the value of the breakOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreakOption() {
        return breakOption;
    }

    /**
     * Sets the value of the breakOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreakOption(String value) {
        this.breakOption = value;
    }

    /**
     * Gets the value of the collectiveObjectIdSender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectiveObjectIdSender() {
        return collectiveObjectIdSender;
    }

    /**
     * Sets the value of the collectiveObjectIdSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectiveObjectIdSender(String value) {
        this.collectiveObjectIdSender = value;
    }

    /**
     * Gets the value of the contractCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractCompletionDate() {
        return contractCompletionDate;
    }

    /**
     * Sets the value of the contractCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractCompletionDate(String value) {
        this.contractCompletionDate = value;
    }

    /**
     * Gets the value of the contractExtensionDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getContractExtensionDuration() {
        return contractExtensionDuration;
    }

    /**
     * Sets the value of the contractExtensionDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setContractExtensionDuration(Duration value) {
        this.contractExtensionDuration = value;
    }

    /**
     * Gets the value of the courtage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getCourtage() {
        return courtage;
    }

    /**
     * Sets the value of the courtage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setCourtage(Amount value) {
        this.courtage = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the debitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitor() {
        return debitor;
    }

    /**
     * Sets the value of the debitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitor(String value) {
        this.debitor = value;
    }

    /**
     * Gets the value of the debitorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitorId() {
        return debitorId;
    }

    /**
     * Sets the value of the debitorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitorId(String value) {
        this.debitorId = value;
    }

    /**
     * Gets the value of the depositAgreed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepositAgreed() {
        return depositAgreed;
    }

    /**
     * Sets the value of the depositAgreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepositAgreed(Boolean value) {
        this.depositAgreed = value;
    }

    /**
     * Gets the value of the depositAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getDepositAmount() {
        return depositAmount;
    }

    /**
     * Sets the value of the depositAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setDepositAmount(Amount value) {
        this.depositAmount = value;
    }

    /**
     * Gets the value of the depositIncreaseType property.
     * 
     * @return
     *     possible object is
     *     {@link DepositIncreaseType }
     *     
     */
    public DepositIncreaseType getDepositIncreaseType() {
        return depositIncreaseType;
    }

    /**
     * Sets the value of the depositIncreaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositIncreaseType }
     *     
     */
    public void setDepositIncreaseType(DepositIncreaseType value) {
        this.depositIncreaseType = value;
    }

    /**
     * Gets the value of the depositPayed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepositPayed() {
        return depositPayed;
    }

    /**
     * Sets the value of the depositPayed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepositPayed(Boolean value) {
        this.depositPayed = value;
    }

    /**
     * Gets the value of the depositType property.
     * 
     * @return
     *     possible object is
     *     {@link DepositType }
     *     
     */
    public DepositType getDepositType() {
        return depositType;
    }

    /**
     * Sets the value of the depositType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepositType }
     *     
     */
    public void setDepositType(DepositType value) {
        this.depositType = value;
    }

    /**
     * Gets the value of the dmiendOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmiendOption() {
        return dmiendOption;
    }

    /**
     * Sets the value of the dmiendOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmiendOption(String value) {
        this.dmiendOption = value;
    }

    /**
     * Gets the value of the dunningIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDunningIndicator() {
        return dunningIndicator;
    }

    /**
     * Sets the value of the dunningIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDunningIndicator(Boolean value) {
        this.dunningIndicator = value;
    }

    /**
     * Gets the value of the dunningLevel property.
     * 
     * @return
     *     possible object is
     *     {@link DunningLevel }
     *     
     */
    public DunningLevel getDunningLevel() {
        return dunningLevel;
    }

    /**
     * Sets the value of the dunningLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DunningLevel }
     *     
     */
    public void setDunningLevel(DunningLevel value) {
        this.dunningLevel = value;
    }

    /**
     * Gets the value of the freeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeFrom() {
        return freeFrom;
    }

    /**
     * Sets the value of the freeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeFrom(String value) {
        this.freeFrom = value;
    }

    /**
     * Gets the value of the heatingCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getHeatingCosts() {
        return heatingCosts;
    }

    /**
     * Sets the value of the heatingCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setHeatingCosts(Amount value) {
        this.heatingCosts = value;
    }

    /**
     * Gets the value of the leaseBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseBeginDate() {
        return leaseBeginDate;
    }

    /**
     * Sets the value of the leaseBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseBeginDate(String value) {
        this.leaseBeginDate = value;
    }

    /**
     * Gets the value of the leaseContractType property.
     * 
     * @return
     *     possible object is
     *     {@link LeaseContractType }
     *     
     */
    public LeaseContractType getLeaseContractType() {
        return leaseContractType;
    }

    /**
     * Sets the value of the leaseContractType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeaseContractType }
     *     
     */
    public void setLeaseContractType(LeaseContractType value) {
        this.leaseContractType = value;
    }

    /**
     * Gets the value of the leaseEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseEndDate() {
        return leaseEndDate;
    }

    /**
     * Sets the value of the leaseEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseEndDate(String value) {
        this.leaseEndDate = value;
    }

    /**
     * Gets the value of the maxNumberOfPerson property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxNumberOfPerson() {
        return maxNumberOfPerson;
    }

    /**
     * Sets the value of the maxNumberOfPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxNumberOfPerson(BigInteger value) {
        this.maxNumberOfPerson = value;
    }

    /**
     * Gets the value of the maxRentalTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaxRentalTime() {
        return maxRentalTime;
    }

    /**
     * Sets the value of the maxRentalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxRentalTime(Duration value) {
        this.maxRentalTime = value;
    }

    /**
     * Gets the value of the minRentalTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinRentalTime() {
        return minRentalTime;
    }

    /**
     * Sets the value of the minRentalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinRentalTime(Duration value) {
        this.minRentalTime = value;
    }

    /**
     * Gets the value of the nation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNation() {
        return nation;
    }

    /**
     * Sets the value of the nation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNation(String value) {
        this.nation = value;
    }

    /**
     * Gets the value of the openItems property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOpenItems() {
        return openItems;
    }

    /**
     * Sets the value of the openItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOpenItems(Amount value) {
        this.openItems = value;
    }

    /**
     * Gets the value of the operatingCostPrepayment property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOperatingCostPrepayment() {
        return operatingCostPrepayment;
    }

    /**
     * Sets the value of the operatingCostPrepayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOperatingCostPrepayment(Amount value) {
        this.operatingCostPrepayment = value;
    }

    /**
     * Gets the value of the operatingCostsSettled property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getOperatingCostsSettled() {
        return operatingCostsSettled;
    }

    /**
     * Sets the value of the operatingCostsSettled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setOperatingCostsSettled(Amount value) {
        this.operatingCostsSettled = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOption(Boolean value) {
        this.option = value;
    }

    /**
     * Gets the value of the parkingSpaceCosts property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getParkingSpaceCosts() {
        return parkingSpaceCosts;
    }

    /**
     * Sets the value of the parkingSpaceCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setParkingSpaceCosts(Amount value) {
        this.parkingSpaceCosts = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setPayment(Amount value) {
        this.payment = value;
    }

    /**
     * Gets the value of the paymentPattern property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPaymentPattern() {
        return paymentPattern;
    }

    /**
     * Sets the value of the paymentPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPaymentPattern(Duration value) {
        this.paymentPattern = value;
    }

    /**
     * Gets the value of the periodsTurnoverRents property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPeriodsTurnoverRents() {
        return periodsTurnoverRents;
    }

    /**
     * Sets the value of the periodsTurnoverRents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPeriodsTurnoverRents(Duration value) {
        this.periodsTurnoverRents = value;
    }

    /**
     * Gets the value of the petsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPetsAllowed() {
        return petsAllowed;
    }

    /**
     * Sets the value of the petsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPetsAllowed(Boolean value) {
        this.petsAllowed = value;
    }

    /**
     * Gets the value of the propertyManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyManager() {
        return propertyManager;
    }

    /**
     * Sets the value of the propertyManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyManager(String value) {
        this.propertyManager = value;
    }

    /**
     * Gets the value of the sector property.
     * 
     * @return
     *     possible object is
     *     {@link Sector }
     *     
     */
    public Sector getSector() {
        return sector;
    }

    /**
     * Sets the value of the sector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sector }
     *     
     */
    public void setSector(Sector value) {
        this.sector = value;
    }

    /**
     * Gets the value of the tenancy property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTenancy() {
        return tenancy;
    }

    /**
     * Sets the value of the tenancy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTenancy(Duration value) {
        this.tenancy = value;
    }

    /**
     * Gets the value of the terminated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTerminated() {
        return terminated;
    }

    /**
     * Sets the value of the terminated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTerminated(Boolean value) {
        this.terminated = value;
    }

    /**
     * Gets the value of the terminationDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTerminationDuration() {
        return terminationDuration;
    }

    /**
     * Sets the value of the terminationDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTerminationDuration(Duration value) {
        this.terminationDuration = value;
    }

    /**
     * Gets the value of the terminationReceiptDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminationReceiptDate() {
        return terminationReceiptDate;
    }

    /**
     * Sets the value of the terminationReceiptDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminationReceiptDate(String value) {
        this.terminationReceiptDate = value;
    }

    /**
     * Gets the value of the turnoverAdjType property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getTurnoverAdjType() {
        return turnoverAdjType;
    }

    /**
     * Sets the value of the turnoverAdjType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setTurnoverAdjType(NumberType value) {
        this.turnoverAdjType = value;
    }

    /**
     * Gets the value of the turnoverCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTurnoverCertificate() {
        return turnoverCertificate;
    }

    /**
     * Sets the value of the turnoverCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTurnoverCertificate(Boolean value) {
        this.turnoverCertificate = value;
    }

    /**
     * Gets the value of the turnoverMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTurnoverMinimum() {
        return turnoverMinimum;
    }

    /**
     * Sets the value of the turnoverMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTurnoverMinimum(Amount value) {
        this.turnoverMinimum = value;
    }

    /**
     * Gets the value of the turnoverRentCap property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTurnoverRentCap() {
        return turnoverRentCap;
    }

    /**
     * Sets the value of the turnoverRentCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTurnoverRentCap(Amount value) {
        this.turnoverRentCap = value;
    }

    /**
     * Gets the value of the turnoverReportingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getTurnoverReportingInterval() {
        return turnoverReportingInterval;
    }

    /**
     * Sets the value of the turnoverReportingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setTurnoverReportingInterval(Duration value) {
        this.turnoverReportingInterval = value;
    }

    /**
     * Gets the value of the turnoverSortiment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurnoverSortiment() {
        return turnoverSortiment;
    }

    /**
     * Sets the value of the turnoverSortiment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurnoverSortiment(String value) {
        this.turnoverSortiment = value;
    }

    /**
*/

    /**
*/

    /**
     * Gets the value of the termUnits property.
     * 
     * @return
     *     possible object is
     *     {@link TermUnits }
     *     
     */
    public TermUnits getTermUnits() {
        return termUnits;
    }

    /**
     * Sets the value of the termUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermUnits }
     *     
     */
    public void setTermUnits(TermUnits value) {
        this.termUnits = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return
     *     possible object is
     *     {@link Terms }
     *     
     */
    public Terms getTerms() {
        return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terms }
     *     
     */
    public void setTerms(Terms value) {
        this.terms = value;
    }

}
