package org.zgif.model.node.entity;

import org.zgif.model.datatype.Amount;
import org.zgif.model.datatype.enumeration.AccountingType;
import org.zgif.model.datatype.enumeration.ProjectType;
import org.zgif.model.datatype.enumeration.ServiceType;
import org.zgif.model.node.group.Address;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.16 at 03:29:57 PM CEST
//


/**
 * <p>Java class for Project complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Project">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="accountingType" type="{}AccountingType" minOccurs="0"/>
 *         &lt;element name="budget" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="capitalization" type="{}iTYPE_DECIMAL" minOccurs="0"/>
 *         &lt;element name="contractAmount" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="costGroup" type="{}ProjectCostCategory" minOccurs="0"/>
 *         &lt;element name="costTransfer" type="{}iTYPE_DECIMAL" minOccurs="0"/>
 *         &lt;element name="craft" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="creditor" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="currency" type="{}iTYPE_CURRENCY" minOccurs="0"/>
 *         &lt;element name="description" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="invoiceAmount" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="numberOfInvoices" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="projectType" type="{}ProjectType" minOccurs="0"/>
 *         &lt;element name="serviceContractId" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="serviceType" type="{}ServiceType" minOccurs="0"/>
 *         &lt;element name="specifications" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="address" type="{}Address" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Project", propOrder = {
    "accountingType",
    "budget",
    "capitalization",
    "contractAmount",
    "costGroup",
    "costTransfer",
    "craft",
    "creditor",
    "currency",
    "description",
    "invoiceAmount",
    "numberOfInvoices",
    "projectType",
    "serviceContractId",
    "serviceType",
    "specifications",
    "address",
    "extensionMap"
})
public class Project
    extends AbstractEntityNode
{

    protected AccountingType accountingType;
    protected Amount budget;
    protected BigDecimal capitalization;
    protected Amount contractAmount;
    protected String costGroup;
    protected BigDecimal costTransfer;
    protected String craft;
    protected String creditor;
    protected String currency;
    protected String description;
    protected Amount invoiceAmount;
    protected BigInteger numberOfInvoices;
    protected ProjectType projectType;
    protected String serviceContractId;
    protected ServiceType serviceType;
    protected String specifications;
    protected Address address;

    /**
     * Gets the value of the accountingType property.
     * 
     * @return
     *     possible object is
     *     {@link AccountingType }
     *     
     */
    public AccountingType getAccountingType() {
        return accountingType;
    }

    /**
     * Sets the value of the accountingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountingType }
     *     
     */
    public void setAccountingType(AccountingType value) {
        this.accountingType = value;
    }

    /**
     * Gets the value of the budget property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getBudget() {
        return budget;
    }

    /**
     * Sets the value of the budget property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setBudget(Amount value) {
        this.budget = value;
    }

    /**
     * Gets the value of the capitalization property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapitalization() {
        return capitalization;
    }

    /**
     * Sets the value of the capitalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapitalization(BigDecimal value) {
        this.capitalization = value;
    }

    /**
     * Gets the value of the contractAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getContractAmount() {
        return contractAmount;
    }

    /**
     * Sets the value of the contractAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setContractAmount(Amount value) {
        this.contractAmount = value;
    }

    /**
     * Gets the value of the costGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostGroup() {
        return costGroup;
    }

    /**
     * Sets the value of the costGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostGroup(String value) {
        this.costGroup = value;
    }

    /**
     * Gets the value of the costTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostTransfer() {
        return costTransfer;
    }

    /**
     * Sets the value of the costTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostTransfer(BigDecimal value) {
        this.costTransfer = value;
    }

    /**
     * Gets the value of the craft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCraft() {
        return craft;
    }

    /**
     * Sets the value of the craft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCraft(String value) {
        this.craft = value;
    }

    /**
     * Gets the value of the creditor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditor() {
        return creditor;
    }

    /**
     * Sets the value of the creditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditor(String value) {
        this.creditor = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the invoiceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * Sets the value of the invoiceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setInvoiceAmount(Amount value) {
        this.invoiceAmount = value;
    }

    /**
     * Gets the value of the numberOfInvoices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfInvoices() {
        return numberOfInvoices;
    }

    /**
     * Sets the value of the numberOfInvoices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfInvoices(BigInteger value) {
        this.numberOfInvoices = value;
    }

    /**
     * Gets the value of the projectType property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectType }
     *     
     */
    public ProjectType getProjectType() {
        return projectType;
    }

    /**
     * Sets the value of the projectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectType }
     *     
     */
    public void setProjectType(ProjectType value) {
        this.projectType = value;
    }

    /**
     * Gets the value of the serviceContractId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceContractId() {
        return serviceContractId;
    }

    /**
     * Sets the value of the serviceContractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceContractId(String value) {
        this.serviceContractId = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setServiceType(ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the specifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * Sets the value of the specifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifications(String value) {
        this.specifications = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
*/

    /**
*/

}
