package org.zgif.model.node.entity;

import org.zgif.model.datatype.Amount;
import org.zgif.model.datatype.Area;
import org.zgif.model.datatype.enumeration.*;
import org.zgif.model.node.group.Address;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;
import java.math.BigInteger;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.16 at 03:29:57 PM CEST
//


/**
 * <p>Java class for Unit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Unit">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="apartmentType" type="{}ApartmentType" minOccurs="0"/>
 *         &lt;element name="archValidFrom" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="archValidTo" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="areaMeasurement" type="{}AreaMeasurement" minOccurs="0"/>
 *         &lt;element name="areaType" type="{}AreaType" minOccurs="0"/>
 *         &lt;element name="autoLift" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="balcony" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="barrierfree" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="certificateOfEligibility" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="condition" type="{}ObjectCondition" minOccurs="0"/>
 *         &lt;element name="courtage" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="endPriceMaintenance" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="garden" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="guestToilet" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="hallHeight" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="hasBuiltinKitchen" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="hasFurniture" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="interiorQuality" type="{}InteriorQuality" minOccurs="0"/>
 *         &lt;element name="isLodgerFlat" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="lanCables" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="lastRefurbishmentDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="lettableArea" type="{}Area" minOccurs="0"/>
 *         &lt;element name="lettableUnits" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="localReferenceRent" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="maxNumberOfPerson" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="minimumDivisible" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="modernisationStatus" type="{}RestorationStatus" minOccurs="0"/>
 *         &lt;element name="nonSmoker" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="numberOfBathrooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfBedrooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfParkingSpaces" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="numberOfRooms" type="{}iTYPE_INTEGER" minOccurs="0"/>
 *         &lt;element name="parkingSpaceType" type="{}ParkingSpaceType" minOccurs="0"/>
 *         &lt;element name="propertyManager" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="summerResidencePractical" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="titleOfExposee" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="useType" type="{}UseType" minOccurs="0"/>
 *         &lt;element name="useTypeCustomer" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="vacancyReason" type="{}VacancyReason" minOccurs="0"/>
 *         &lt;element name="address" type="{}Address" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Unit", propOrder = {
    "apartmentType",
    "archValidFrom",
    "archValidTo",
    "areaMeasurement",
    "areaType",
    "autoLift",
    "balcony",
    "barrierfree",
    "certificateOfEligibility",
    "condition",
    "courtage",
    "endPriceMaintenance",
    "garden",
    "guestToilet",
    "hallHeight",
    "hasBuiltinKitchen",
    "hasFurniture",
    "interiorQuality",
    "isLodgerFlat",
    "lanCables",
    "lastRefurbishmentDate",
    "lettableArea",
    "lettableUnits",
    "localReferenceRent",
    "maxNumberOfPerson",
    "minimumDivisible",
    "modernisationStatus",
    "nonSmoker",
    "numberOfBathrooms",
    "numberOfBedrooms",
    "numberOfParkingSpaces",
    "numberOfRooms",
    "parkingSpaceType",
    "propertyManager",
    "summerResidencePractical",
    "titleOfExposee",
    "useType",
    "useTypeCustomer",
    "vacancyReason",
    "address",
    "extensionMap"
})
public class Unit
    extends AbstractEntityNode
{

    protected ApartmentType apartmentType;
    protected String archValidFrom;
    protected String archValidTo;
    protected AreaMeasurement areaMeasurement;
    protected AreaType areaType;
    protected Boolean autoLift;
    protected Boolean balcony;
    protected Boolean barrierfree;
    protected Boolean certificateOfEligibility;
    protected ObjectCondition condition;
    protected Amount courtage;
    protected String endPriceMaintenance;
    protected Boolean garden;
    protected Boolean guestToilet;
    protected BigDecimal hallHeight;
    protected Boolean hasBuiltinKitchen;
    protected Boolean hasFurniture;
    protected InteriorQuality interiorQuality;
    protected Boolean isLodgerFlat;
    protected Boolean lanCables;
    protected String lastRefurbishmentDate;
    protected Area lettableArea;
    protected BigDecimal lettableUnits;
    protected Amount localReferenceRent;
    protected BigInteger maxNumberOfPerson;
    protected BigInteger minimumDivisible;
    protected RestorationStatus modernisationStatus;
    protected Boolean nonSmoker;
    protected BigInteger numberOfBathrooms;
    protected BigInteger numberOfBedrooms;
    protected BigInteger numberOfParkingSpaces;
    protected BigInteger numberOfRooms;
    protected ParkingSpaceType parkingSpaceType;
    protected String propertyManager;
    protected Boolean summerResidencePractical;
    protected String titleOfExposee;
    protected UseType useType;
    protected String useTypeCustomer;
    protected VacancyReason vacancyReason;
    protected Address address;

    /**
     * Gets the value of the apartmentType property.
     * 
     * @return
     *     possible object is
     *     {@link ApartmentType }
     *     
     */
    public ApartmentType getApartmentType() {
        return apartmentType;
    }

    /**
     * Sets the value of the apartmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApartmentType }
     *     
     */
    public void setApartmentType(ApartmentType value) {
        this.apartmentType = value;
    }

    /**
     * Gets the value of the archValidFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchValidFrom() {
        return archValidFrom;
    }

    /**
     * Sets the value of the archValidFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchValidFrom(String value) {
        this.archValidFrom = value;
    }

    /**
     * Gets the value of the archValidTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchValidTo() {
        return archValidTo;
    }

    /**
     * Sets the value of the archValidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchValidTo(String value) {
        this.archValidTo = value;
    }

    /**
     * Gets the value of the areaMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link AreaMeasurement }
     *     
     */
    public AreaMeasurement getAreaMeasurement() {
        return areaMeasurement;
    }

    /**
     * Sets the value of the areaMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaMeasurement }
     *     
     */
    public void setAreaMeasurement(AreaMeasurement value) {
        this.areaMeasurement = value;
    }

    /**
     * Gets the value of the areaType property.
     * 
     * @return
     *     possible object is
     *     {@link AreaType }
     *     
     */
    public AreaType getAreaType() {
        return areaType;
    }

    /**
     * Sets the value of the areaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaType }
     *     
     */
    public void setAreaType(AreaType value) {
        this.areaType = value;
    }

    /**
     * Gets the value of the autoLift property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoLift() {
        return autoLift;
    }

    /**
     * Sets the value of the autoLift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoLift(Boolean value) {
        this.autoLift = value;
    }

    /**
     * Gets the value of the balcony property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBalcony() {
        return balcony;
    }

    /**
     * Sets the value of the balcony property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBalcony(Boolean value) {
        this.balcony = value;
    }

    /**
     * Gets the value of the barrierfree property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBarrierfree() {
        return barrierfree;
    }

    /**
     * Sets the value of the barrierfree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBarrierfree(Boolean value) {
        this.barrierfree = value;
    }

    /**
     * Gets the value of the certificateOfEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCertificateOfEligibility() {
        return certificateOfEligibility;
    }

    /**
     * Sets the value of the certificateOfEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCertificateOfEligibility(Boolean value) {
        this.certificateOfEligibility = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectCondition }
     *     
     */
    public ObjectCondition getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectCondition }
     *     
     */
    public void setCondition(ObjectCondition value) {
        this.condition = value;
    }

    /**
     * Gets the value of the courtage property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getCourtage() {
        return courtage;
    }

    /**
     * Sets the value of the courtage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setCourtage(Amount value) {
        this.courtage = value;
    }

    /**
     * Gets the value of the endPriceMaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPriceMaintenance() {
        return endPriceMaintenance;
    }

    /**
     * Sets the value of the endPriceMaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPriceMaintenance(String value) {
        this.endPriceMaintenance = value;
    }

    /**
     * Gets the value of the garden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGarden() {
        return garden;
    }

    /**
     * Sets the value of the garden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGarden(Boolean value) {
        this.garden = value;
    }

    /**
     * Gets the value of the guestToilet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGuestToilet() {
        return guestToilet;
    }

    /**
     * Sets the value of the guestToilet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGuestToilet(Boolean value) {
        this.guestToilet = value;
    }

    /**
     * Gets the value of the hallHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHallHeight() {
        return hallHeight;
    }

    /**
     * Sets the value of the hallHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHallHeight(BigDecimal value) {
        this.hallHeight = value;
    }

    /**
     * Gets the value of the hasBuiltinKitchen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasBuiltinKitchen() {
        return hasBuiltinKitchen;
    }

    /**
     * Sets the value of the hasBuiltinKitchen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasBuiltinKitchen(Boolean value) {
        this.hasBuiltinKitchen = value;
    }

    /**
     * Gets the value of the hasFurniture property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasFurniture() {
        return hasFurniture;
    }

    /**
     * Sets the value of the hasFurniture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasFurniture(Boolean value) {
        this.hasFurniture = value;
    }

    /**
     * Gets the value of the interiorQuality property.
     * 
     * @return
     *     possible object is
     *     {@link InteriorQuality }
     *     
     */
    public InteriorQuality getInteriorQuality() {
        return interiorQuality;
    }

    /**
     * Sets the value of the interiorQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteriorQuality }
     *     
     */
    public void setInteriorQuality(InteriorQuality value) {
        this.interiorQuality = value;
    }

    /**
     * Gets the value of the isLodgerFlat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLodgerFlat() {
        return isLodgerFlat;
    }

    /**
     * Sets the value of the isLodgerFlat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLodgerFlat(Boolean value) {
        this.isLodgerFlat = value;
    }

    /**
     * Gets the value of the lanCables property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLanCables() {
        return lanCables;
    }

    /**
     * Sets the value of the lanCables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLanCables(Boolean value) {
        this.lanCables = value;
    }

    /**
     * Gets the value of the lastRefurbishmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastRefurbishmentDate() {
        return lastRefurbishmentDate;
    }

    /**
     * Sets the value of the lastRefurbishmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastRefurbishmentDate(String value) {
        this.lastRefurbishmentDate = value;
    }

    /**
     * Gets the value of the lettableArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getLettableArea() {
        return lettableArea;
    }

    /**
     * Sets the value of the lettableArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setLettableArea(Area value) {
        this.lettableArea = value;
    }

    /**
     * Gets the value of the lettableUnits property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLettableUnits() {
        return lettableUnits;
    }

    /**
     * Sets the value of the lettableUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLettableUnits(BigDecimal value) {
        this.lettableUnits = value;
    }

    /**
     * Gets the value of the localReferenceRent property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLocalReferenceRent() {
        return localReferenceRent;
    }

    /**
     * Sets the value of the localReferenceRent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLocalReferenceRent(Amount value) {
        this.localReferenceRent = value;
    }

    /**
     * Gets the value of the maxNumberOfPerson property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxNumberOfPerson() {
        return maxNumberOfPerson;
    }

    /**
     * Sets the value of the maxNumberOfPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxNumberOfPerson(BigInteger value) {
        this.maxNumberOfPerson = value;
    }

    /**
     * Gets the value of the minimumDivisible property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinimumDivisible() {
        return minimumDivisible;
    }

    /**
     * Sets the value of the minimumDivisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinimumDivisible(BigInteger value) {
        this.minimumDivisible = value;
    }

    /**
     * Gets the value of the modernisationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RestorationStatus }
     *     
     */
    public RestorationStatus getModernisationStatus() {
        return modernisationStatus;
    }

    /**
     * Sets the value of the modernisationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestorationStatus }
     *     
     */
    public void setModernisationStatus(RestorationStatus value) {
        this.modernisationStatus = value;
    }

    /**
     * Gets the value of the nonSmoker property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNonSmoker() {
        return nonSmoker;
    }

    /**
     * Sets the value of the nonSmoker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonSmoker(Boolean value) {
        this.nonSmoker = value;
    }

    /**
     * Gets the value of the numberOfBathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBathrooms() {
        return numberOfBathrooms;
    }

    /**
     * Sets the value of the numberOfBathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBathrooms(BigInteger value) {
        this.numberOfBathrooms = value;
    }

    /**
     * Gets the value of the numberOfBedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBedrooms() {
        return numberOfBedrooms;
    }

    /**
     * Sets the value of the numberOfBedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBedrooms(BigInteger value) {
        this.numberOfBedrooms = value;
    }

    /**
     * Gets the value of the numberOfParkingSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfParkingSpaces() {
        return numberOfParkingSpaces;
    }

    /**
     * Sets the value of the numberOfParkingSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfParkingSpaces(BigInteger value) {
        this.numberOfParkingSpaces = value;
    }

    /**
     * Gets the value of the numberOfRooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfRooms() {
        return numberOfRooms;
    }

    /**
     * Sets the value of the numberOfRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfRooms(BigInteger value) {
        this.numberOfRooms = value;
    }

    /**
     * Gets the value of the parkingSpaceType property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingSpaceType }
     *     
     */
    public ParkingSpaceType getParkingSpaceType() {
        return parkingSpaceType;
    }

    /**
     * Sets the value of the parkingSpaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingSpaceType }
     *     
     */
    public void setParkingSpaceType(ParkingSpaceType value) {
        this.parkingSpaceType = value;
    }

    /**
     * Gets the value of the propertyManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyManager() {
        return propertyManager;
    }

    /**
     * Sets the value of the propertyManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyManager(String value) {
        this.propertyManager = value;
    }

    /**
     * Gets the value of the summerResidencePractical property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSummerResidencePractical() {
        return summerResidencePractical;
    }

    /**
     * Sets the value of the summerResidencePractical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSummerResidencePractical(Boolean value) {
        this.summerResidencePractical = value;
    }

    /**
     * Gets the value of the titleOfExposee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleOfExposee() {
        return titleOfExposee;
    }

    /**
     * Sets the value of the titleOfExposee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleOfExposee(String value) {
        this.titleOfExposee = value;
    }

    /**
     * Gets the value of the useType property.
     * 
     * @return
     *     possible object is
     *     {@link UseType }
     *     
     */
    public UseType getUseType() {
        return useType;
    }

    /**
     * Sets the value of the useType property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseType }
     *     
     */
    public void setUseType(UseType value) {
        this.useType = value;
    }

    /**
     * Gets the value of the useTypeCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseTypeCustomer() {
        return useTypeCustomer;
    }

    /**
     * Sets the value of the useTypeCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseTypeCustomer(String value) {
        this.useTypeCustomer = value;
    }

    /**
     * Gets the value of the vacancyReason property.
     * 
     * @return
     *     possible object is
     *     {@link VacancyReason }
     *     
     */
    public VacancyReason getVacancyReason() {
        return vacancyReason;
    }

    /**
     * Sets the value of the vacancyReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link VacancyReason }
     *     
     */
    public void setVacancyReason(VacancyReason value) {
        this.vacancyReason = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
*/

    /**
*/

}
