package org.zgif.model.node.entity;

import org.zgif.model.datatype.Amount;
import org.zgif.model.datatype.Area;
import org.zgif.model.datatype.enumeration.ValuationMethod;
import org.zgif.model.node.group.EnergyRating;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.08.16 at 03:29:57 PM CEST
//


/**
 * <p>Java class for Valuation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Valuation">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractEntityNode">
 *       &lt;sequence>
 *         &lt;element name="buildingInDevelopmentState" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="contractRentDebit" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="currency" type="{}iTYPE_CURRENCY" minOccurs="0"/>
 *         &lt;element name="discountRate" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="effectiveArea" type="{}Area" minOccurs="0"/>
 *         &lt;element name="effectiveAreaIndustry" type="{}Area" minOccurs="0"/>
 *         &lt;element name="effectiveAreaOffice" type="{}Area" minOccurs="0"/>
 *         &lt;element name="effectiveAreaOther" type="{}Area" minOccurs="0"/>
 *         &lt;element name="effectiveAreaResidential" type="{}Area" minOccurs="0"/>
 *         &lt;element name="effectiveAreaTrade" type="{}Area" minOccurs="0"/>
 *         &lt;element name="expertName" type="{}iTYPE_STRING" minOccurs="0"/>
 *         &lt;element name="fairValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="grossFairValue" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="internalValuation" type="{}iTYPE_BOOLEAN" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYield" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYieldIndustry" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYieldOffice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYieldOther" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYieldResidential" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="lostSustainablyGrossYieldTrade" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="method" type="{}ValuationMethod" minOccurs="0"/>
 *         &lt;element name="ownershipShare" type="{}iTYPE_DOUBLE" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYield" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYieldIndustry" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYieldOffice" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYieldOther" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYieldResidential" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="sustainablyGrossYieldTrade" type="{}Amount" minOccurs="0"/>
 *         &lt;element name="vacantEffectiveAreaIndustry" type="{}Area" minOccurs="0"/>
 *         &lt;element name="vacantEffectiveAreaOffice" type="{}Area" minOccurs="0"/>
 *         &lt;element name="vacantEffectiveAreaOther" type="{}Area" minOccurs="0"/>
 *         &lt;element name="vacantEffectiveAreaResidential" type="{}Area" minOccurs="0"/>
 *         &lt;element name="vacantEffectiveAreaTrade" type="{}Area" minOccurs="0"/>
 *         &lt;element name="valuationDate" type="{}iTYPE_LOCALDATE" minOccurs="0"/>
 *         &lt;element name="energyRating" type="{}EnergyRating" minOccurs="0"/>
 *         &lt;element name="extensionMap" type="{}ExtensionMap" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Valuation", propOrder = {
    "buildingInDevelopmentState",
    "contractRentDebit",
    "currency",
    "discountRate",
    "effectiveArea",
    "effectiveAreaIndustry",
    "effectiveAreaOffice",
    "effectiveAreaOther",
    "effectiveAreaResidential",
    "effectiveAreaTrade",
    "expertName",
    "fairValue",
    "grossFairValue",
    "internalValuation",
    "lostSustainablyGrossYield",
    "lostSustainablyGrossYieldIndustry",
    "lostSustainablyGrossYieldOffice",
    "lostSustainablyGrossYieldOther",
    "lostSustainablyGrossYieldResidential",
    "lostSustainablyGrossYieldTrade",
    "method",
    "ownershipShare",
    "sustainablyGrossYield",
    "sustainablyGrossYieldIndustry",
    "sustainablyGrossYieldOffice",
    "sustainablyGrossYieldOther",
    "sustainablyGrossYieldResidential",
    "sustainablyGrossYieldTrade",
    "vacantEffectiveAreaIndustry",
    "vacantEffectiveAreaOffice",
    "vacantEffectiveAreaOther",
    "vacantEffectiveAreaResidential",
    "vacantEffectiveAreaTrade",
    "valuationDate",
    "energyRating",
    "extensionMap"
})
public class Valuation
    extends AbstractEntityNode
{

    protected Boolean buildingInDevelopmentState;
    protected Amount contractRentDebit;
    protected String currency;
    protected BigDecimal discountRate;
    protected Area effectiveArea;
    protected Area effectiveAreaIndustry;
    protected Area effectiveAreaOffice;
    protected Area effectiveAreaOther;
    protected Area effectiveAreaResidential;
    protected Area effectiveAreaTrade;
    protected String expertName;
    protected Amount fairValue;
    protected Amount grossFairValue;
    protected Boolean internalValuation;
    protected Amount lostSustainablyGrossYield;
    protected Amount lostSustainablyGrossYieldIndustry;
    protected Amount lostSustainablyGrossYieldOffice;
    protected Amount lostSustainablyGrossYieldOther;
    protected Amount lostSustainablyGrossYieldResidential;
    protected Amount lostSustainablyGrossYieldTrade;
    protected ValuationMethod method;
    protected BigDecimal ownershipShare;
    protected Amount sustainablyGrossYield;
    protected Amount sustainablyGrossYieldIndustry;
    protected Amount sustainablyGrossYieldOffice;
    protected Amount sustainablyGrossYieldOther;
    protected Amount sustainablyGrossYieldResidential;
    protected Amount sustainablyGrossYieldTrade;
    protected Area vacantEffectiveAreaIndustry;
    protected Area vacantEffectiveAreaOffice;
    protected Area vacantEffectiveAreaOther;
    protected Area vacantEffectiveAreaResidential;
    protected Area vacantEffectiveAreaTrade;
    protected String valuationDate;
    protected EnergyRating energyRating;

    /**
     * Gets the value of the buildingInDevelopmentState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBuildingInDevelopmentState() {
        return buildingInDevelopmentState;
    }

    /**
     * Sets the value of the buildingInDevelopmentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBuildingInDevelopmentState(Boolean value) {
        this.buildingInDevelopmentState = value;
    }

    /**
     * Gets the value of the contractRentDebit property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getContractRentDebit() {
        return contractRentDebit;
    }

    /**
     * Sets the value of the contractRentDebit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setContractRentDebit(Amount value) {
        this.contractRentDebit = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the discountRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * Sets the value of the discountRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountRate(BigDecimal value) {
        this.discountRate = value;
    }

    /**
     * Gets the value of the effectiveArea property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveArea() {
        return effectiveArea;
    }

    /**
     * Sets the value of the effectiveArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveArea(Area value) {
        this.effectiveArea = value;
    }

    /**
     * Gets the value of the effectiveAreaIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveAreaIndustry() {
        return effectiveAreaIndustry;
    }

    /**
     * Sets the value of the effectiveAreaIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveAreaIndustry(Area value) {
        this.effectiveAreaIndustry = value;
    }

    /**
     * Gets the value of the effectiveAreaOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveAreaOffice() {
        return effectiveAreaOffice;
    }

    /**
     * Sets the value of the effectiveAreaOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveAreaOffice(Area value) {
        this.effectiveAreaOffice = value;
    }

    /**
     * Gets the value of the effectiveAreaOther property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveAreaOther() {
        return effectiveAreaOther;
    }

    /**
     * Sets the value of the effectiveAreaOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveAreaOther(Area value) {
        this.effectiveAreaOther = value;
    }

    /**
     * Gets the value of the effectiveAreaResidential property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveAreaResidential() {
        return effectiveAreaResidential;
    }

    /**
     * Sets the value of the effectiveAreaResidential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveAreaResidential(Area value) {
        this.effectiveAreaResidential = value;
    }

    /**
     * Gets the value of the effectiveAreaTrade property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getEffectiveAreaTrade() {
        return effectiveAreaTrade;
    }

    /**
     * Sets the value of the effectiveAreaTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setEffectiveAreaTrade(Area value) {
        this.effectiveAreaTrade = value;
    }

    /**
     * Gets the value of the expertName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpertName() {
        return expertName;
    }

    /**
     * Sets the value of the expertName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpertName(String value) {
        this.expertName = value;
    }

    /**
     * Gets the value of the fairValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getFairValue() {
        return fairValue;
    }

    /**
     * Sets the value of the fairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setFairValue(Amount value) {
        this.fairValue = value;
    }

    /**
     * Gets the value of the grossFairValue property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getGrossFairValue() {
        return grossFairValue;
    }

    /**
     * Sets the value of the grossFairValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setGrossFairValue(Amount value) {
        this.grossFairValue = value;
    }

    /**
     * Gets the value of the internalValuation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInternalValuation() {
        return internalValuation;
    }

    /**
     * Sets the value of the internalValuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInternalValuation(Boolean value) {
        this.internalValuation = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYield property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYield() {
        return lostSustainablyGrossYield;
    }

    /**
     * Sets the value of the lostSustainablyGrossYield property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYield(Amount value) {
        this.lostSustainablyGrossYield = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYieldIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYieldIndustry() {
        return lostSustainablyGrossYieldIndustry;
    }

    /**
     * Sets the value of the lostSustainablyGrossYieldIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYieldIndustry(Amount value) {
        this.lostSustainablyGrossYieldIndustry = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYieldOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYieldOffice() {
        return lostSustainablyGrossYieldOffice;
    }

    /**
     * Sets the value of the lostSustainablyGrossYieldOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYieldOffice(Amount value) {
        this.lostSustainablyGrossYieldOffice = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYieldOther property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYieldOther() {
        return lostSustainablyGrossYieldOther;
    }

    /**
     * Sets the value of the lostSustainablyGrossYieldOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYieldOther(Amount value) {
        this.lostSustainablyGrossYieldOther = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYieldResidential property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYieldResidential() {
        return lostSustainablyGrossYieldResidential;
    }

    /**
     * Sets the value of the lostSustainablyGrossYieldResidential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYieldResidential(Amount value) {
        this.lostSustainablyGrossYieldResidential = value;
    }

    /**
     * Gets the value of the lostSustainablyGrossYieldTrade property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getLostSustainablyGrossYieldTrade() {
        return lostSustainablyGrossYieldTrade;
    }

    /**
     * Sets the value of the lostSustainablyGrossYieldTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setLostSustainablyGrossYieldTrade(Amount value) {
        this.lostSustainablyGrossYieldTrade = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link ValuationMethod }
     *     
     */
    public ValuationMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValuationMethod }
     *     
     */
    public void setMethod(ValuationMethod value) {
        this.method = value;
    }

    /**
     * Gets the value of the ownershipShare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOwnershipShare() {
        return ownershipShare;
    }

    /**
     * Sets the value of the ownershipShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOwnershipShare(BigDecimal value) {
        this.ownershipShare = value;
    }

    /**
     * Gets the value of the sustainablyGrossYield property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYield() {
        return sustainablyGrossYield;
    }

    /**
     * Sets the value of the sustainablyGrossYield property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYield(Amount value) {
        this.sustainablyGrossYield = value;
    }

    /**
     * Gets the value of the sustainablyGrossYieldIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYieldIndustry() {
        return sustainablyGrossYieldIndustry;
    }

    /**
     * Sets the value of the sustainablyGrossYieldIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYieldIndustry(Amount value) {
        this.sustainablyGrossYieldIndustry = value;
    }

    /**
     * Gets the value of the sustainablyGrossYieldOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYieldOffice() {
        return sustainablyGrossYieldOffice;
    }

    /**
     * Sets the value of the sustainablyGrossYieldOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYieldOffice(Amount value) {
        this.sustainablyGrossYieldOffice = value;
    }

    /**
     * Gets the value of the sustainablyGrossYieldOther property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYieldOther() {
        return sustainablyGrossYieldOther;
    }

    /**
     * Sets the value of the sustainablyGrossYieldOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYieldOther(Amount value) {
        this.sustainablyGrossYieldOther = value;
    }

    /**
     * Gets the value of the sustainablyGrossYieldResidential property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYieldResidential() {
        return sustainablyGrossYieldResidential;
    }

    /**
     * Sets the value of the sustainablyGrossYieldResidential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYieldResidential(Amount value) {
        this.sustainablyGrossYieldResidential = value;
    }

    /**
     * Gets the value of the sustainablyGrossYieldTrade property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getSustainablyGrossYieldTrade() {
        return sustainablyGrossYieldTrade;
    }

    /**
     * Sets the value of the sustainablyGrossYieldTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setSustainablyGrossYieldTrade(Amount value) {
        this.sustainablyGrossYieldTrade = value;
    }

    /**
     * Gets the value of the vacantEffectiveAreaIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getVacantEffectiveAreaIndustry() {
        return vacantEffectiveAreaIndustry;
    }

    /**
     * Sets the value of the vacantEffectiveAreaIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setVacantEffectiveAreaIndustry(Area value) {
        this.vacantEffectiveAreaIndustry = value;
    }

    /**
     * Gets the value of the vacantEffectiveAreaOffice property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getVacantEffectiveAreaOffice() {
        return vacantEffectiveAreaOffice;
    }

    /**
     * Sets the value of the vacantEffectiveAreaOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setVacantEffectiveAreaOffice(Area value) {
        this.vacantEffectiveAreaOffice = value;
    }

    /**
     * Gets the value of the vacantEffectiveAreaOther property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getVacantEffectiveAreaOther() {
        return vacantEffectiveAreaOther;
    }

    /**
     * Sets the value of the vacantEffectiveAreaOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setVacantEffectiveAreaOther(Area value) {
        this.vacantEffectiveAreaOther = value;
    }

    /**
     * Gets the value of the vacantEffectiveAreaResidential property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getVacantEffectiveAreaResidential() {
        return vacantEffectiveAreaResidential;
    }

    /**
     * Sets the value of the vacantEffectiveAreaResidential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setVacantEffectiveAreaResidential(Area value) {
        this.vacantEffectiveAreaResidential = value;
    }

    /**
     * Gets the value of the vacantEffectiveAreaTrade property.
     * 
     * @return
     *     possible object is
     *     {@link Area }
     *     
     */
    public Area getVacantEffectiveAreaTrade() {
        return vacantEffectiveAreaTrade;
    }

    /**
     * Sets the value of the vacantEffectiveAreaTrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link Area }
     *     
     */
    public void setVacantEffectiveAreaTrade(Area value) {
        this.vacantEffectiveAreaTrade = value;
    }

    /**
     * Gets the value of the valuationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuationDate() {
        return valuationDate;
    }

    /**
     * Sets the value of the valuationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuationDate(String value) {
        this.valuationDate = value;
    }

    /**
     * Gets the value of the energyRating property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyRating }
     *     
     */
    public EnergyRating getEnergyRating() {
        return energyRating;
    }

    /**
     * Sets the value of the energyRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyRating }
     *     
     */
    public void setEnergyRating(EnergyRating value) {
        this.energyRating = value;
    }

    /**
*/

    /**
*/

}
