package org.zgif.model.datatype.enumeration;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 03:29:57 PM CEST 
//



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocationType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="NOT_SPECIFIED"/>
 *     &lt;enumeration value="WS"/>
 *     &lt;enumeration value="WR"/>
 *     &lt;enumeration value="WA"/>
 *     &lt;enumeration value="WB"/>
 *     &lt;enumeration value="MD"/>
 *     &lt;enumeration value="MI"/>
 *     &lt;enumeration value="MK"/>
 *     &lt;enumeration value="GE"/>
 *     &lt;enumeration value="GI"/>
 *     &lt;enumeration value="SO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocationType")
@XmlEnum
public enum LocationType {

    NOT_SPECIFIED,
    WS,
    WR,
    WA,
    WB,
    MD,
    MI,
    MK,
    GE,
    GI,
    SO;

    public String value() {
        return name();
    }

    public static LocationType fromValue(String v) {
        return valueOf(v);
    }

}
