package org.zgif.model.datatype.enumeration;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 03:29:57 PM CEST 
//



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OccupancyState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OccupancyState">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="RENTED_AND_OCCUPIED_LEASER"/>
 *     &lt;enumeration value="RENTED_AND_OCCUPIED_OWNER"/>
 *     &lt;enumeration value="RENTED_NOT_OCCUPIED"/>
 *     &lt;enumeration value="OUTSTANDING_RENT_WRITTEN_OFF"/>
 *     &lt;enumeration value="PREARRANGED"/>
 *     &lt;enumeration value="VACANCY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OccupancyState")
@XmlEnum
public enum OccupancyState {

    RENTED_AND_OCCUPIED_LEASER,
    RENTED_AND_OCCUPIED_OWNER,
    RENTED_NOT_OCCUPIED,
    OUTSTANDING_RENT_WRITTEN_OFF,
    PREARRANGED,
    VACANCY;

    public String value() {
        return name();
    }

    public static OccupancyState fromValue(String v) {
        return valueOf(v);
    }

}
