package org.zgif.model.datatype.enumeration;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 03:29:57 PM CEST 
//



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OwnershipType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OwnershipType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="DIRECT_PROPERTY"/>
 *     &lt;enumeration value="LEASEHOLD"/>
 *     &lt;enumeration value="OTHER"/>
 *     &lt;enumeration value="FREEHOLDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OwnershipType")
@XmlEnum
public enum OwnershipType {

    DIRECT_PROPERTY,
    LEASEHOLD,
    OTHER,
    FREEHOLDER;

    public String value() {
        return name();
    }

    public static OwnershipType fromValue(String v) {
        return valueOf(v);
    }

}
