package org.zgif.model.datatype.enumeration;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.16 at 03:29:57 PM CEST 
//



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PeriodValueType">
 *   &lt;restriction base="{}iTYPE_STRING">
 *     &lt;enumeration value="ACTUAL"/>
 *     &lt;enumeration value="PLAN"/>
 *     &lt;enumeration value="FORECAST"/>
 *     &lt;enumeration value="BUDGET"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PeriodValueType")
@XmlEnum
public enum PeriodValueType {

    ACTUAL,
    PLAN,
    FORECAST,
    BUDGET,
    OTHER;

    public String value() {
        return name();
    }

    public static PeriodValueType fromValue(String v) {
        return valueOf(v);
    }

}
